import test from 'node:test';
import assert from 'node:assert/strict';
import {bounds,selectionIds,transformLayers,snapMove,resizeBox,marqueeIds,alignLayers} from '../src/studio-geometry.js';
const layers=[{id:'icon',groupId:'cost',x:10,y:20,w:40,h:40},{id:'value',groupId:'cost',type:'text',fontSize:14,x:20,y:30,w:20,h:20},{id:'other',x:110,y:20,w:40,h:40}];
test('cost selects as a group; individual selection bypasses it',()=>{assert.deepEqual(selectionIds(layers,'value'),['icon','value']);assert.deepEqual(selectionIds(layers,'value',true),['value'])});
test('group resize and move preserve relative geometry, membership and text scale',()=>{const ids=['icon','value'],b=bounds(layers.slice(0,2)),out=transformLayers(layers,ids,b,{x:50,y:60,w:80,h:80});assert.deepEqual([out[0].x,out[0].y,out[0].w],[50,60,80]);assert.deepEqual([out[1].x,out[1].y,out[1].w,out[1].fontSize],[70,80,40,28]);assert.equal(out[1].groupId,'cost');assert.equal(out[2],layers[2]);assert.deepEqual(JSON.parse(JSON.stringify(out)),out)});
test('snapping aligns grid and guides and can be bypassed',()=>{const b={x:12,y:21,w:40,h:40};const r=snapMove(b,6,6,{spacing:10,threshold:3,width:360,height:540});assert.equal(r.dx,8);assert.equal(r.dy,9);assert.equal(r.guides.length,2);assert.deepEqual(snapMove(b,6,6,{enabled:false}),{dx:6,dy:6,guides:[]})});
test('resize keeps opposite corner and locks aspect with Shift',()=>{const b={x:10,y:20,w:100,h:50},r=resizeBox(b,'nw',-20,-10,true);assert.deepEqual(r,{x:-10,y:10,w:120,h:60});const c=resizeBox(b,'se',24,6,false,10);assert.equal(c.w,120);assert.equal(c.h,60)});
test('marquee includes visible unlocked contained layers and distribution retains endpoints',()=>{assert.deepEqual(marqueeIds(layers.map(l=>({...l,visible:true})),{x:5,y:15,w:50,h:50}),['icon','value']);const a=[{id:'a',x:0,y:0,w:10,h:10},{id:'b',x:25,y:0,w:10,h:10},{id:'c',x:90,y:0,w:10,h:10}];assert.deepEqual(alignLayers(a,['a','b','c'],'distribute-x').map(l=>l.x),[0,45,90])});
