import {readFileSync,writeFileSync,mkdirSync,existsSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
import {decodePng,encodePng,contentBox,resample} from '../../tools/concept-cutout.mjs';
import {ENEMY_POSES} from '../../src/content/enemyArt.js';
const poses=['seed','buff','wounded','afflicted','projectile','guard','guardHit','hurt'];
const selected=process.argv.slice(2);const ids=selected.length?selected:ENEMY_POSES;
const displayScales={};
mkdirSync('assets/enemy-states',{recursive:true});
for(const id of ids){
 const sheetPath=`art/enemy-states/sheets/${id}.png`;
 if(!existsSync(sheetPath))throw Error(`Missing state sheet: ${id}`);
 const cells=`art/enemy-states/cells/${id}`,frames=`art/enemy-states/frames/${id}`;
 mkdirSync(cells,{recursive:true});mkdirSync(frames,{recursive:true});
 execFileSync(process.execPath,['tools/painted-poses.mjs','--sheet',sheetPath,'--class',id,'--out',frames,'--mask-only','--checker-pockets','--tolerance','75',
  '--speck',id==='charredColossus'?'0.0003':'0.00004'],{stdio:'pipe'});
 const sheet=decodePng(readFileSync(`${frames}/${id}_mask.png`));
 // Generated sheets can shift their gutters. Find the emptiest separating
 // row/columns near the requested layout instead of cutting through feet.
 const boundary=(axis,expected,range,start,end)=>{
  let best=Math.round(expected),score=Infinity,distance=Infinity;
  for(let n=Math.floor(expected-range);n<=Math.ceil(expected+range);n++){
   let ink=0;
   for(let k=start;k<end;k++){
    const x=axis==='x'?n:k,y=axis==='x'?k:n;
    if(sheet.px[(y*sheet.width+x)*4+3]>40)ink++;
   }
   if(ink<score||(ink===score&&Math.abs(n-expected)<distance)){best=n;score=ink;distance=Math.abs(n-expected);}
  }
  return best;
 };
 const middle=boundary('y',sheet.height/2,sheet.height*.15,0,sheet.width);
 const rows=[0,middle,sheet.height];
 const columns=[0,1].map(r=>[0,...[1,2,3].map(c=>boundary('x',c*sheet.width/4,sheet.width*.09,rows[r],rows[r+1])),sheet.width]);
 writeFileSync(`${frames}/layout.json`,JSON.stringify({rows,columns},null,2)+'\n');
 const images=[];
 for(let i=0;i<8;i++){
  const row=Math.floor(i/4),col=i%4;
  const x0=columns[row][col],x1=columns[row][col+1];
  const y0=rows[row],y1=rows[row+1];
  const w=x1-x0,h=y1-y0,px=Buffer.alloc(w*h*4);
  for(let y=0;y<h;y++)for(let x=0;x<w;x++){
   const from=((y+y0)*sheet.width+x+x0)*sheet.bpp,to=(y*w+x)*4;
   if(sheet.bpp<3){px[to]=px[to+1]=px[to+2]=sheet.px[from];px[to+3]=sheet.bpp===2?sheet.px[from+1]:255;}
   else {px[to]=sheet.px[from];px[to+1]=sheet.px[from+1];px[to+2]=sheet.px[from+2];px[to+3]=sheet.bpp===4?sheet.px[from+3]:255;}
  }
  const cell=`${cells}/${poses[i]}.png`;writeFileSync(cell,encodePng(w,h,px));
  const img=decodePng(readFileSync(cell));
  images.push({img,box:contentBox(img)});
 }
 const scale=Math.min(...images.map(({box:b})=>Math.min(348/(b.x1-b.x0+1),344/(b.y1-b.y0+1))));
 const seed=images[0].box;
 const oldIdle=contentBox(decodePng(readFileSync(`assets/enemy-poses/${id}_idle.png`)));
 // Export headroom must not shrink the character when a weapon is raised.
 // The sheet's idle seed registers all seven states to the approved idle.
 displayScales[id]=Number(((oldIdle.y1-oldIdle.y0+1)/((seed.y1-seed.y0+1)*scale)).toFixed(5));
 for(let i=1;i<8;i++){
  const {img,box:b}=images[i],w=b.x1-b.x0+1,h=b.y1-b.y0+1;
  const dw=Math.max(1,Math.round(w*scale)),dh=Math.max(1,Math.round(h*scale));
  const small=resample(img,b.x0,b.y0,w,h,dw,dh),px=Buffer.alloc(384*384*4);
  const left=Math.round((384-dw)/2),top=365-dh;
  for(let y=0;y<dh;y++)small.px.copy(px,((top+y)*384+left)*4,y*dw*4,(y+1)*dw*4);
  writeFileSync(`assets/enemy-states/${id}_${poses[i]}.png`,encodePng(384,384,px));
 }
 console.log(`${id}: 7 state sprites exported`);
}
if(!selected.length){
 mkdirSync('asset-data/enemy-states',{recursive:true});writeFileSync('asset-data/enemy-states/manifest.json',JSON.stringify({canvas:[384,384],ground:364,facing:'left',poses:poses.slice(1),enemies:ENEMY_POSES,displayScales},null,2)+'\n');
 writeFileSync('src/content/enemyStateArt.js','// Generated by art/enemy-states/build.mjs; do not edit.\nexport const ENEMY_STATE_SCALE = '+JSON.stringify(displayScales,null,2)+';\n');
}
