const {chromium}=require('C:/Users/suprbludude/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const path=require('path');
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'}),page=await browser.newPage({viewport:{width:1536,height:1100}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:8765/art/webp-maps-2026-09-19/scene-layers/index.html');
for(const s of await page.evaluate(()=>SCENES.scenes)){await page.locator(`button[data-id="${s.id}"]`).click();await page.locator('#floor').evaluate(im=>im.decode());await page.locator('#background').evaluate(im=>im.decode());const dims=await page.locator('#floor').evaluate(im=>[im.naturalWidth,im.naturalHeight]);if(dims[0]!==1536||dims[1]!==1024)throw Error('Wrong dimensions');}
await page.locator('#showFloor').uncheck();if(await page.locator('#floor').isVisible())throw Error('Floor toggle failed');await page.screenshot({path:path.join(__dirname,'previews/background-only.png'),fullPage:true});
await page.locator('#showFloor').check();await page.locator('#showBackground').uncheck();if(await page.locator('#background').isVisible())throw Error('Background toggle failed');await page.screenshot({path:path.join(__dirname,'previews/floor-only.png'),fullPage:true});
await page.locator('#showBackground').check();await page.locator('#showGuides').check();await page.locator('#showDialogue').check();if(!await page.locator('#dialogue').isVisible())throw Error('Dialogue toggle failed');await page.screenshot({path:path.join(__dirname,'previews/gallery-desktop.png'),fullPage:true});
await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(__dirname,'previews/gallery-mobile.png'),fullPage:true});if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Mobile overflow');
await page.goto('http://127.0.0.1:8765/art/webp-maps-2026-09-19/legacy-dungeons/index.html');await page.getByRole('link',{name:/View layered scene/}).click();if(!page.url().endsWith('#BS-ENV-01'))throw Error('Map link failed');if(errors.length)throw Error(errors.join('\n'));console.log('PASS: all 24 layers load; 12 scenes; independent layer toggles; dialogue and position guides; mobile sizing; dungeon links; no browser errors.');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
