import assert from 'node:assert/strict';
import { existsSync } from 'node:fs';
import { contentBundle } from '../src/content/index.js';
import { createRegistries } from '../src/model/registries.js';
import { createRunState } from '../src/model/state.js';
import { createRng } from '../src/engine/rng.js';
import { createSaveManager, createMemoryStorage } from '../src/engine/save.js';
import { buildActMap } from '../src/engine/actmap.js';
import { LEGACY_DUNGEONS, LEGACY_SCENES, beginDungeon, dungeonNeighbors, dungeonNode, dungeonNodeAction, dungeonChoices, dungeonScene, travelDungeon, chooseDungeon, continueDungeon, resolveDungeonNode, escapeChance, legacyDungeonProblems } from '../src/model/legacyDungeon.js';

const registries = createRegistries(contentBundle);
for (const def of LEGACY_DUNGEONS) {
  const rng = createRng(721), saves = createSaveManager(createMemoryStorage());
  const run = createRunState({ seed: 721, classId: 'reaver', registries });
  run.seatOrder = ['weald','marches','reach'];
  run.mapGraph = buildActMap(registries, rng, 'weald', 1);
  const parent = Object.values(run.mapGraph.nodes).find(n => n.type === 'boss');
  run.mapNodeId = parent.id; run.path = [parent.id]; run.floor = parent.floor;
  beginDungeon(run, def, parent.id);
  assert.equal(def.nodes.length, 24);
  assert.equal(dungeonNeighbors(run).length, 2);
  assert.ok(existsSync(def.map));
  assert.equal(travelDungeon(run, dungeonNeighbors(run)[0]), false, 'cannot skip a decision');
  const seen = new Set(), queue = [def.entrance];
  while (queue.length) {
    const id = queue.shift(); if (seen.has(id)) continue; seen.add(id);
    queue.push(...dungeonNeighbors(run, id));
  }
  assert.equal(seen.size, 24, 'every location reachable');
  for (const n of def.nodes) {
    assert.ok(n.lore && n.reply && n.speaker);
    assert.ok(registries.encounters.has(n.encounter), n.encounter);
    run.legacyDungeon.current = n.id;
    assert.ok(dungeonScene(run), n.id);
    assert.equal(dungeonNodeAction(run), n.kind === 'shrine' ? 'rest' : n.kind === 'cache' ? 'treasure' : ['fight', 'boss'].includes(n.kind) ? 'combat' : 'dialogue', n.id);
  }
  run.legacyDungeon.current = def.entrance;
  chooseDungeon(run, 'listen', rng); continueDungeon(run);
  assert.equal(travelDungeon(run, dungeonNeighbors(run)[0]), true);
  const hostile = def.nodes.find(n => n.kind === 'encounter');
  run.legacyDungeon.previous = def.entrance; run.legacyDungeon.current = hostile.id;
  run.legacyDungeon.visited.push(hostile.id);
  const receipt = chooseDungeon(run, 'flee', { int: () => 1 });
  assert.equal(receipt.action, 'retreat');
  assert.equal(chooseDungeon(run, 'flee', { int: () => { throw Error('rerolled'); } }), receipt);
  saves.saveRun(run, rng);
  const loaded = saves.loadRun(registries);
  assert.ok(loaded, JSON.stringify(saves.runStatus()));
  assert.deepEqual(loaded.legacyDungeon, run.legacyDungeon, 'pending escape round-trips');
  continueDungeon(loaded);
  assert.equal(loaded.legacyDungeon.current, def.entrance);
  assert.ok(!loaded.legacyDungeon.resolved.includes(hostile.id));
  continueDungeon(run); run.legacyDungeon.current = hostile.id;
  assert.equal(chooseDungeon(run, 'flee', { int: () => 100 }).action, 'combat');
  assert.equal(continueDungeon(run), 'combat');
  resolveDungeonNode(run);
  assert.equal(run.legacyDungeon.cleared, false);
  assert.deepEqual(dungeonChoices(run).map(c => c.id), ['leave'], 'cannot farm a fight');
  const cache = def.nodes.find(n => n.kind === 'cache');
  run.legacyDungeon.current = cache.id;
  const before = run.cinders;
  chooseDungeon(run, 'listen', rng); chooseDungeon(run, 'listen', rng); continueDungeon(run);
  assert.equal(run.cinders, before + 20);
  assert.throws(() => chooseDungeon(run, 'listen', rng), /Unavailable/);
  const shrine = def.nodes.find(n => n.kind === 'shrine');
  run.legacyDungeon.current = shrine.id;
  run.hp = Math.max(1, run.maxHp - 20);
  const hpBeforeRest = run.hp;
  assert.equal(chooseDungeon(run, 'listen', rng).action, 'rest');
  assert.equal(run.hp, hpBeforeRest, 'dialogue must not auto-heal or skip rest choices');
  assert.ok(!run.legacyDungeon.resolved.includes(shrine.id));
  saves.saveRun(run, rng);
  assert.equal(saves.loadRun(registries).legacyDungeon.pending.action, 'rest');
  assert.equal(continueDungeon(run), 'rest');
  assert.equal(travelDungeon(run, dungeonNeighbors(run)[0]), false);
  saves.saveRun(run, rng);
  assert.deepEqual(saves.loadRun(registries).legacyDungeon.activeRest, { nodeId: shrine.id, refilled: false });
  resolveDungeonNode(run);
  assert.equal(run.legacyDungeon.activeRest, undefined);
  assert.deepEqual(dungeonChoices(run).map(c => c.id), ['leave']);
  run.legacyDungeon.current = def.bossNode;
  assert.equal(dungeonScene(run).boss, true);
  chooseDungeon(run, 'fight', rng); continueDungeon(run);
  resolveDungeonNode(run);
  assert.equal(run.legacyDungeon.cleared, true);
  assert.deepEqual(legacyDungeonProblems(run), []);
  saves.saveRun(run, rng);
  assert.equal(saves.loadRun(registries).legacyDungeon.cleared, true);
  run.attributes.dexterity = 100; assert.equal(escapeChance(run), 85);
  run.attributes.dexterity = -100; assert.equal(escapeChance(run), 10);
  run.legacyDungeon.current = 'missing'; assert.ok(legacyDungeonProblems(run).length);
  console.log(`PASS ${def.name}: graph, scenes, decisions, escape, save, rewards and boss clear`);
}
for (const s of LEGACY_SCENES) for (const k of ['floor','background']) assert.ok(existsSync(s[k]), s[k]);
assert.equal(LEGACY_SCENES.length, 12);
console.log('PASS all 24 scene layers exist');
