import {createRequire} from 'node:module';import {readFileSync,writeFileSync,mkdirSync,existsSync} from 'node:fs';import {dirname,join} from 'node:path';import {fileURLToPath} from 'node:url';import {decodePng,contentBox} from '../../tools/concept-cutout.mjs';
const require=createRequire(import.meta.url),{chromium}=require('playwright');const here=dirname(fileURLToPath(import.meta.url));const m=JSON.parse(readFileSync(join(here,'manifest.json'),'utf8'));let n=0;const problems=[];
if(m.outfits.length!==16)problems.push('Expected 16 outfits');
for(const o of m.outfits){if(o.frames.map(f=>f.pose).join(',')!=='idle,guard,attack1,attack2,attack3,attack4,hit')problems.push(o.id+' missing state');
for(const f of o.frames){const im=decodePng(readFileSync(join(here,f.file)));if(im.bpp!==4||im.width!==640||im.height!==640)problems.push(f.file+' wrong format');const b=contentBox(im);if(b.x0<4||b.x1>635||b.y0<4||b.y1>635)problems.push(f.file+' touches frame border');if(b.y1<597||b.y1>602)problems.push(f.file+' ground '+b.y1);n++}
for(const p of Object.values(o.menu))if(!existsSync(join(here,p)))problems.push('Missing '+p)}
const executablePath=[process.env.CHROME,'C:/Program Files/Google/Chrome/Application/chrome.exe','C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'].find(p=>p&&existsSync(p));
const browser=await chromium.launch({headless:true,...executablePath?{executablePath}:{}});const page=await browser.newPage({viewport:{width:1600,height:1500},reducedMotion:'reduce'});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:4276');await page.waitForFunction(()=>window.artManifest?.outfits.length===16);await page.getByRole('button',{name:'Combat frames',exact:true}).click();mkdirSync(join(here,'inspection'),{recursive:true});
for(const c of ['rogue','reaver','starseer','herald']){await page.locator('#class').selectOption(c);await page.locator('.frames img').evaluateAll(imgs=>Promise.all(imgs.map(i=>i.decode())));await page.screenshot({path:join(here,'inspection',c+'-combat.png'),fullPage:true});}
await page.getByRole('button',{name:'Menu & details',exact:true}).click();for(const c of ['rogue','reaver','starseer','herald']){await page.locator('#class').selectOption(c);await page.locator('.menu-grid img').evaluateAll(imgs=>Promise.all(imgs.map(i=>i.decode())));await page.screenshot({path:join(here,'inspection',c+'-menu.png'),fullPage:true});}
await page.getByRole('button',{name:'Animation preview',exact:true}).click();await page.locator('#class').selectOption('all');let played=0;
for(const o of m.outfits){await page.locator('#outfit').selectOption(o.id);for(const action of ['attack','guard','hit','idle']){await page.locator('#action').selectOption(action);const count=action==='attack'?6:action==='idle'?1:3;for(let i=0;i<count;i++){await page.locator('.player img').evaluate(i=>i.decode());await page.getByRole('button',{name:'Next frame',exact:true}).click();played++}}}
await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Menu & details',exact:true}).click();await page.locator('#class').selectOption('rogue');await page.locator('.menu-grid img').evaluateAll(imgs=>Promise.all(imgs.map(i=>i.decode())));await page.screenshot({path:join(here,'inspection','phone-menu.png'),fullPage:false});
const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);if(overflow)problems.push('Phone horizontal overflow');
await browser.close();problems.push(...errors);
const report={outfits:m.outfits.length,combatFiles:n,portraitFiles:m.outfits.length,animationStatesDecoded:played,problems,visualFacing:'Review inspection contact sheets separately; direction cannot be proved by file checks.'};
writeFileSync(join(here,'inspection','checks.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));if(problems.length)process.exitCode=1;
