const $=s=>document.querySelector(s), dataset=window.DUNGEONS;
let dungeon=dataset.dungeons[0],mode='atlas',states={},selected,combat=null;
const themeColors={olive:['#20271d','#88936a'],indigo:['#1b2437','#a9bed1'],ember:['#302321','#b96b42']};
const state=()=>states[dungeon.id]??=( {current:dungeon.entrance,previous:dungeon.entrance,resolved:new Set(),visited:new Set([dungeon.entrance]),cleared:false,read:new Set(),messages:{}} );
const node=id=>dungeon.nodes.find(n=>n.id===id);
const neighbors=id=>dungeon.edges.flatMap(e=>e.a===id?[e.b]:e.b===id?[e.a]:[]);
const chance=()=>Math.max(10,Math.min(85,40+3*(Number($('#dex').value||10)-10)));
function announce(text){$('#announce').textContent=text}
function switchDungeon(id){dungeon=dataset.dungeons.find(d=>d.id===id);selected=state().current;combat=null;render()}
function select(id){selected=id;render();announce(`${node(id).name} selected`)}
function enter(id){const s=state();if(!neighbors(s.current).includes(id)||(!s.cleared&&!s.resolved.has(s.current)&&s.current!==dungeon.entrance))return;s.previous=s.current;s.current=id;s.visited.add(id);selected=id;combat=null;render()}
function resolve(message){const s=state();s.resolved.add(selected);s.messages[selected]=message;render();announce(message)}
function flee(){const roll=new Uint32Array(1);crypto.getRandomValues(roll);const r=1+Math.floor(roll[0]/4294967296*100),p=chance(),s=state();if(r<=p){const from=selected;s.messages[from]=`Escape succeeded: rolled ${r}, needed ${p} or lower. The encounter remains unresolved.`;s.current=s.previous;selected=s.current;combat=null;s.messages[selected]=`You escaped ${node(from).name} (${r} ≤ ${p}%). You can choose another road.`;render();announce('Escape succeeded. Retreated to previous node.')}else{combat=selected;s.messages[selected]=`Escape failed: rolled ${r}, needed ${p} or lower. The encounter begins.`;render();announce('Escape failed. Encounter begins.')}}
function button(text,action,disabled=false){const b=document.createElement('button');b.textContent=text;b.disabled=disabled;b.addEventListener('click',action);return b}
function render(){const s=state(),n=node(selected||s.current);selected=n.id;document.body.dataset.theme=dungeon.theme;$('#title').textContent=dungeon.name;$('#tabs').replaceChildren(...dataset.dungeons.map(d=>{const b=button(d.name,()=>switchDungeon(d.id));b.classList.toggle('active',d.id===dungeon.id);b.setAttribute('aria-pressed',d.id===dungeon.id);return b}));const image=`../webp/${dungeon.assetId}.webp`;$('#painting').src=image;$('#painting').alt=`${dungeon.name}, painted dungeon map with 24 connected locations`;$('#explore').classList.toggle('active',mode==='explore');$('#atlas').classList.toggle('active',mode==='atlas');
const known=new Set([...s.visited,...[...s.visited].flatMap(neighbors)]);const visible=mode==='atlas'||s.cleared?dungeon.nodes:dungeon.nodes.filter(n=>known.has(n.id));
const color=themeColors[dungeon.theme];let svg=`<defs><radialGradient id="edge-haze"><stop offset="45%" stop-color="${color[1]}" stop-opacity="0"/><stop offset="100%" stop-color="${color[1]}" stop-opacity=".30"/></radialGradient><mask id="discovered"><rect width="1536" height="1024" fill="white"/>${[...s.visited].map(id=>{const p=node(id);return `<ellipse cx="${p.x*15.36}" cy="${p.y*10.24}" rx="175" ry="130" fill="black"/>`}).join('')}</mask></defs>`;
if($('#fog').checked){svg+=`<rect width="1536" height="1024" fill="url(#edge-haze)"/>`;if(mode==='explore'&&!s.cleared)svg+=`<rect width="1536" height="1024" fill="${color[0]}" opacity=".94" mask="url(#discovered)"/>`}
svg+=dungeon.edges.filter(e=>mode==='atlas'||s.cleared||s.visited.has(e.a)||s.visited.has(e.b)).map(e=>{const a=node(e.a),b=node(e.b),points=[[a.x,a.y],...e.via,[b.x,b.y]];return `<polyline class="route" points="${points.map(([x,y])=>`${x*15.36},${y*10.24}`).join(' ')}"/>`}).join('');$('#routes').innerHTML=svg;
$('#markers').replaceChildren(...visible.map(p=>{const b=button(p.number,()=>select(p.id));b.className=`marker ${p.id===selected?'selected':''} ${mode==='explore'&&p.id===s.current?'current':''} ${s.resolved.has(p.id)?'done':''} ${p.kind==='boss'?'boss':''}`;b.style.left=p.x+'%';b.style.top=p.y+'%';b.title=`${p.id} · ${p.name} · ${p.kind}`;b.setAttribute('aria-label',b.title);b.setAttribute('aria-pressed',p.id===selected);return b}));
$('#progress').textContent=s.cleared?'Dungeon cleared · Boss defeated':mode==='atlas'?'Atlas · 24 locations · Full route review':`Explore · ${s.resolved.size}/24 resolved · At ${node(s.current).name}`;$('#progress').className=s.cleared?'clear':'';$('#lanes').textContent=`2 entrance lanes · ${dungeon.lanes.join(' / ')}`;
const panel=$('#panel');panel.innerHTML='';const meta=document.createElement('div');meta.className='node-meta';meta.textContent=`${n.id} · ${n.kind[0].toUpperCase()+n.kind.slice(1)}${s.resolved.has(n.id)?' · Resolved':''}`;const title=document.createElement('h2');title.textContent=n.name;const detail=document.createElement('div');detail.className='detail-image';detail.style.backgroundImage=`url('${image}')`;detail.style.backgroundPosition=`${n.x}% ${n.y}%`;detail.setAttribute('role','img');detail.setAttribute('aria-label',n.name+' location detail');const speaker=document.createElement('p');speaker.className='speaker';speaker.textContent=n.speaker;const speech=document.createElement('p');speech.className='speech';speech.textContent='“'+n.lore+'”';panel.append(meta,title,detail,speaker,speech); const scene=window.SCENES?.scenes.find(a=>a.region===dungeon.id && n.number>=Number(a.nodeStart.slice(-2)) && n.number<=Number(a.nodeEnd.slice(-2))); if(scene){detail.style.backgroundImage=`url("../scene-layers/${scene.preview}")`;detail.style.backgroundSize="cover";detail.style.backgroundPosition="center"; const link=document.createElement("a");link.href="../scene-layers/index.html#"+scene.id;link.textContent="View layered scene · "+scene.id;panel.append(link);}
if(s.read.has(n.id)){const extra=document.createElement('p');extra.textContent=n.reply;panel.append(extra)}
if(s.messages[n.id]){const result=document.createElement('p');result.className='result';result.textContent=s.messages[n.id];panel.append(result)}
const choices=document.createElement('div');choices.className='choices';panel.append(choices);
choices.append(button(s.read.has(n.id)?'Close lore detail':n.speaker==='You'?'Read the traces':'Listen further',()=>{s.read.has(n.id)?s.read.delete(n.id):s.read.add(n.id);render()}));
if(mode==='atlas'){const hint=document.createElement('p');hint.className='hint';hint.textContent=n.kind==='boss'?'Boss victory clears the dungeon. Optional rooms remain available afterward.':['encounter','fight'].includes(n.kind)?`Encounter options: ${n.kind==='encounter'?'hear them out, challenge, or escape':'fight or escape'}. Current escape chance: ${chance()}%.`:'Lore and observations use this same dialogue view. Switch to Explore to walk the routes.';panel.append(hint);return}
if(n.id!==s.current){const adjacent=neighbors(s.current).includes(n.id),unlocked=s.cleared||s.resolved.has(s.current)||s.current===dungeon.entrance;choices.append(button(adjacent?'Travel here':'Follow a connecting road first',()=>enter(n.id),!adjacent||!unlocked));if(!unlocked){const p=document.createElement('p');p.className='hint';p.textContent='Resolve your current location before moving on.';panel.append(p)}return}
if(combat===n.id){choices.append(button('Simulate victory',()=>{combat=null;if(n.kind==='boss'){s.cleared=true;resolve(`${dungeon.boss} defeated. Dungeon cleared. All routes remain open for unfinished lore.`)}else resolve('Encounter won. The road is open.')}));choices.append(button('Simulate defeat · Return to entrance',()=>{combat=null;s.current=dungeon.entrance;s.previous=dungeon.entrance;selected=s.current;s.messages[selected]='Defeated in the preview. Returned to the entrance; resolved locations remain resolved.';render()}));return}
if(s.resolved.has(n.id)||s.cleared){if(!s.resolved.has(n.id))choices.append(button('Record remaining lore',()=>resolve('Lore recorded.')));const p=document.createElement('p');p.className='hint';p.textContent='Select a connected numbered location to continue.';panel.append(p);return}
if(n.kind==='boss'){choices.append(button(`Confront ${dungeon.boss}`,()=>{combat=n.id;render()}));choices.append(button('Withdraw to the threshold',()=>{s.current=s.previous;selected=s.current;render()}));}
else if(['encounter','fight'].includes(n.kind)){if(n.kind==='encounter')choices.append(button('Hear them out · Pass peacefully',()=>{s.read.add(n.id);resolve('You lower your weapon and listen. The passage opens without a fight.')}));choices.append(button(n.kind==='fight'?'Stand and fight':'Challenge them · Fight',()=>{combat=n.id;render()}));choices.append(button(`Try to flee · ${chance()}% chance`,flee));const p=document.createElement('p');p.className='hint';p.textContent='Draft rule: 40% + 3 percentage points per Dexterity above 10 (10–85%). Roll 1–100 at or below the chance. Failure starts combat; success retreats.';panel.append(p)}
else choices.append(button(n.kind==='entrance'?'Enter the dungeon':n.kind==='gate'?'Cross the threshold':n.kind==='dialogue'?'Thank them and continue':n.kind==='cache'?'Inspect and record the find':n.kind==='shrine'?'Pause at the shrine':'Record observation',()=>{s.read.add(n.id);resolve(n.kind==='entrance'?'Choose either road from the entrance.':'Recorded in your dungeon journal.')}));
}
$('#atlas').onclick=()=>{mode='atlas';combat=null;render()};$('#explore').onclick=()=>{mode='explore';selected=state().current;render()};$('#fog').onchange=render;$('#dex').onchange=()=>{$('#dex').value=Math.max(1,Math.min(40,Number($('#dex').value)||10));render()};$('#reset').onclick=()=>{delete states[dungeon.id];selected=state().current;combat=null;render()};switchDungeon(dungeon.id);
