import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
const {chromium}=await import(process.env.POSE_STUDIO_PLAYWRIGHT?pathToFileURL(process.env.POSE_STUDIO_PLAYWRIGHT).href:'playwright');
const out=process.env.POSE_STUDIO_EVIDENCE;if(!out)throw Error('Set POSE_STUDIO_EVIDENCE outside the repository');await mkdir(out,{recursive:true});
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH,headless:true});
const checks=[],errors=[];const check=message=>{checks.push(message);console.log(message);};
try{
 const page=await browser.newPage({viewport:{width:550,height:1000},hasTouch:true,acceptDownloads:true});page.on('pageerror',e=>errors.push(e.message));
 await page.goto((process.env.POSE_STUDIO_URL||'http://127.0.0.1:4320')+'/pose-studio/index.html');await page.locator('[data-preset="shield"]').click();
 const draft=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('ashenspire.pose-studio.draft.v1')));
 const change=async(selector,value)=>{await page.locator(selector).fill(String(value));await page.locator(selector).press('Tab');};
 const mouseDrag=async(a,b)=>{await page.mouse.move(a.x,a.y);await page.mouse.down();await page.mouse.move(b.x,b.y,{steps:12});await page.mouse.up();};
 await change('#effect-size-number',320);assert.equal((await draft()).clips[0].size,320);await page.locator('#undo').click();assert.equal((await draft()).clips[0].size,180);await page.locator('#redo').click();assert.equal((await draft()).clips[0].size,320);
 await page.locator('#effect-size').focus();await page.keyboard.press('ArrowRight');await page.keyboard.press('ArrowRight');await page.keyboard.press('Tab');assert.equal((await draft()).clips[0].size,322);
 await page.locator('#quick-hide').click();assert.ok((await draft()).clips[0].muted);await page.locator('#quick-hide').click();assert.ok(!(await draft()).clips[0].muted);
 await page.locator('#quick-duplicate').click();assert.equal((await draft()).clips.length,2);await page.locator('#quick-remove').click();assert.equal((await draft()).clips.length,1);await page.locator('#undo').click();assert.equal((await draft()).clips.length,2);await page.locator('#quick-remove').click();
 check('550px: visible size slider, numeric size, hide/show, duplicate, removal and undo');
 await change('#effect-size-number',180);
 const beforeZoom=await draft();await page.locator('#zoom-in').click({clickCount:4});assert.equal(await page.locator('#zoom-value').textContent(),'200%');assert.deepEqual(await draft(),beforeZoom);
 await page.locator('#direction').selectOption('left');await page.locator('#stage').scrollIntoViewIfNeeded();
 const stagePoint=async(corner=false)=>page.evaluate(async({corner})=>{
   const {sample}=await import('/pose-studio/model.mjs');const p=JSON.parse(localStorage.getItem('ashenspire.pose-studio.draft.v1')),c=sample(p,Number(document.querySelector('#scrub').value)).effects[0],b=document.querySelector('#stage').getBoundingClientRect(),z=Number(document.querySelector('#preview-zoom').value)/100;
   const r=c.rotation*Math.PI/180,d=corner?c.size/2:0;let x=c.x*1000+d*Math.cos(r)+d*Math.sin(r),y=c.y*600+d*Math.sin(r)-d*Math.cos(r);if(document.querySelector('#direction').value==='left')x=1000-x;
   return {x:b.left+((x-500)*z+500)*b.width/1000,y:b.top+((y-300)*z+300)*b.height/600,width:b.width};
 },{corner});
 let pt=await stagePoint(),old=(await draft()).clips[0];await mouseDrag(pt,{x:pt.x+15,y:pt.y+8});let c=(await draft()).clips[0];assert.ok(Math.abs(c.x-old.x+15*1000/pt.width/2)<=1);assert.ok(Math.abs(c.y-old.y-8*1000/pt.width/2)<=1);
 await page.locator('#edit-effect').click();await page.locator('#effect-advanced > summary').click();await change('[data-field="rotation"]',25);await page.locator('#close-tool').click();await page.locator('#stage').scrollIntoViewIfNeeded();pt=await stagePoint(true);const center=await stagePoint();old=(await draft()).clips[0];await mouseDrag(pt,{x:center.x+(pt.x-center.x)*1.35,y:center.y+(pt.y-center.y)*1.35});assert.ok(Math.abs((await draft()).clips[0].size-old.size*1.35)<=2,JSON.stringify({old,actual:(await draft()).clips[0],pt,center}));
 const beforeCancel=await draft();pt=await stagePoint();await page.mouse.move(pt.x,pt.y);await page.mouse.down();await page.mouse.move(pt.x+30,pt.y+10,{steps:5});await page.keyboard.press('Escape');await page.mouse.up();assert.deepEqual(await draft(),beforeCancel);
 await page.locator('#pan-preview').click();pt=await stagePoint();await mouseDrag(pt,{x:pt.x+20,y:pt.y+20});assert.deepEqual(await draft(),beforeCancel);await page.locator('#pan-preview').click();await page.locator('#zoom-fit').click();await page.locator('#direction').selectOption('right');
 check('zoom is view-only; mirrored/zoomed move, rotated corner resize, pan and Escape cancellation work');
 await page.locator('#add-effect').click();assert.ok(await page.locator('#library-dock').isVisible());assert.equal(await page.locator('#tool-dialog').evaluate(e=>e.matches(':modal')),false);await page.locator('#search').fill('ward');await page.locator('[data-effect="wardCatch"]').click();assert.equal((await draft()).clips.length,2);
 await page.setViewportSize({width:1440,height:1100});await page.locator('#search').fill('heel');
 const lane=page.locator('[data-layer="behind"] .drop-rail');await lane.scrollIntoViewIfNeeded();const box=await lane.boundingBox();
 await page.locator('[data-effect="heelScuff"]').dragTo(lane,{targetPosition:{x:box.width*.25,y:15}});
 c=(await draft()).clips.at(-1);assert.equal(c.effect,'heelScuff');assert.equal(c.layer,'behind');assert.ok(Math.abs(c.offset-300)<=8);assert.equal(c.anchor,'feet');
 assert.equal(await page.locator('.clip-film img').count(),18);check('native library drop uses the requested layer and exact time; six sprite thumbnails per effect');
 const id=c.id,clip=page.locator(`[data-clip="${id}"]`);await page.locator('#tracks').scrollIntoViewIfNeeded();let a=await clip.boundingBox();let target=await page.locator('[data-layer="aura"] .drop-rail').boundingBox();
 await mouseDrag({x:a.x+a.width/2,y:a.y+30},{x:a.x+a.width/2+40,y:target.y+15});c=(await draft()).clips.find(x=>x.id===id);assert.equal(c.layer,'aura');assert.ok(c.offset>300);assert.equal(c.duration,420);
 await clip.scrollIntoViewIfNeeded();a=await clip.locator('[data-trim="end"]').boundingBox();old=c;await mouseDrag({x:a.x+a.width/2,y:a.y+25},{x:a.x+a.width/2+30,y:a.y+25});c=(await draft()).clips.find(x=>x.id===id);assert.ok(c.duration>old.duration);assert.equal(c.offset,old.offset);
 a=await clip.locator('[data-trim="start"]').boundingBox();old=c;await mouseDrag({x:a.x+a.width/2,y:a.y+25},{x:a.x+a.width/2+15,y:a.y+25});c=(await draft()).clips.find(x=>x.id===id);assert.ok(c.offset>old.offset);assert.equal(c.offset+c.duration,old.offset+old.duration);
 await clip.focus();old=c;await page.keyboard.press('ArrowRight');assert.equal((await draft()).clips.find(x=>x.id===id).offset,old.offset+10);await page.keyboard.press('Shift+ArrowRight');assert.equal((await draft()).clips.find(x=>x.id===id).duration,old.duration+10);
 check('strip drag preserves grab offset and duration across layers; both timing handles and keyboard edits persist');
 await page.locator('#timeline-detail').check();assert.ok(await page.locator('.timeline-scroll').evaluate(e=>e.scrollWidth>e.clientWidth));await page.locator('#timeline-detail').uncheck();
 await page.locator('#search').fill('ward');await page.locator('#zoom-character').click();await page.locator('#stage').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'direct-desktop.png'),fullPage:true});
 await page.setViewportSize({width:390,height:844});await page.locator('#zoom-fit').click();await clip.scrollIntoViewIfNeeded();
 const cdp=await page.context().newCDPSession(page);const touchDrag=async(a,b)=>{await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[a]});for(let i=1;i<=12;i++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:a.x+(b.x-a.x)*i/12,y:a.y+(b.y-a.y)*i/12}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});};
 a=await clip.boundingBox();old=(await draft()).clips.find(x=>x.id===id);await touchDrag({x:a.x+a.width/2,y:a.y+30},{x:a.x+a.width/2-20,y:a.y+30});c=(await draft()).clips.find(x=>x.id===id);assert.ok(c.offset<old.offset);assert.equal(c.duration,old.duration);
 await page.locator(`[data-remove="${id}"]`).tap();assert.equal((await draft()).clips.length,2);await page.locator('#undo').tap();assert.equal((await draft()).clips.length,3);
 await page.locator('#effect-size-number').focus();await page.keyboard.press('Backspace');assert.equal((await draft()).clips.length,3);await page.locator('#stage').focus();await page.keyboard.press('Delete');assert.equal((await draft()).clips.length,2);await page.locator('#undo').click();
 check('390px real touch strip drag, visible row removal, undo and safe Delete shortcut');
 await page.setViewportSize({width:550,height:1000});await page.locator('#add-effect').tap();await page.locator('#search').fill('poisonSeep');await page.locator('#library-dock').evaluate(e=>{e.scrollIntoView({block:'start'});window.scrollBy(0,120);});
 const grip=page.locator('[data-effect="poisonSeep"] .effect-grip');a=await grip.boundingBox();target=await page.locator('[data-layer="front"] .drop-rail').boundingBox();assert.ok(target.y+20<1000,JSON.stringify({message:'Touch drop target is visible',source:a,target}));
 await touchDrag({x:a.x+a.width/2,y:a.y+a.height/2},{x:target.x+target.width*.2,y:target.y+18});c=(await draft()).clips.at(-1);assert.equal(c.effect,'poisonSeep');assert.equal(c.layer,'front');assert.ok(Math.abs(c.offset-240)<=8);check('real touch library grip drops onto a timeline lane without a blocking modal');
 await page.setViewportSize({width:550,height:1000});await page.locator('#zoom-character').click();await page.locator('#stage').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'direct-550.png'),fullPage:true});
 await page.setViewportSize({width:390,height:844});await page.locator('#stage').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'direct-phone.png'),fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 for(const selector of ['#quick-remove','#quick-hide','#quick-duplicate','#effect-size-number','#zoom-fit']){const b=await page.locator(selector).boundingBox();assert.ok(b.width>=44&&b.height>=44,selector);}
 const saved=await draft();const event=page.waitForEvent('download');await page.locator('#save').click();await (await event).saveAs(path.join(out,'direct-editing.pose.json'));await page.reload();await page.locator('.clip').first().waitFor();assert.deepEqual(await draft(),saved);assert.equal(await page.locator('#zoom-value').textContent(),'100%');check('portable download and reload preserve effect transforms and timing; camera resets independently');
 assert.deepEqual(errors,[]);await writeFile(path.join(out,'direct-checks.json'),JSON.stringify({checks,errors},null,2));console.log(JSON.stringify({checks,errors},null,2));
}finally{await browser.close();}
