import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
const {chromium}=await import(process.env.POSE_STUDIO_PLAYWRIGHT?pathToFileURL(process.env.POSE_STUDIO_PLAYWRIGHT).href:'playwright');
const out=process.env.POSE_STUDIO_EVIDENCE;if(!out)throw Error('Set POSE_STUDIO_EVIDENCE outside the repository');await mkdir(out,{recursive:true});
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH,headless:true}),errors=[],checks=[];
try{
 const page=await browser.newPage({viewport:{width:1440,height:1100},acceptDownloads:true,hasTouch:true});page.on('pageerror',e=>errors.push(e.message));
 await page.goto((process.env.POSE_STUDIO_URL||'http://127.0.0.1:4318')+'/pose-studio/index.html');await page.locator('.effect').first().waitFor();
 const draft=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('ashenspire.pose-studio.draft.v1')));
 assert.equal(await page.locator('#guide').getAttribute('open'),'');await page.locator('[data-preset="ward"]').click();assert.equal(await page.locator('#guide').getAttribute('open'),null);checks.push('first visit offers templates; choosing one exposes the canvas');
 await page.locator('#add-effect').tap();assert.equal(await page.locator('#search').evaluate(el=>el===document.activeElement),true);
 await page.locator('#search').fill('no-such-effect');assert.match(await page.locator('#effects').textContent(),/No effects match/);await page.locator('#reset-search').click();assert.equal(await page.locator('.effect').count(),80);checks.push('search has a clear recovery path');
 await page.locator('[data-effect="wardCatch"]').click();const visible=await page.evaluate(async()=>{const {sample}=await import('/pose-studio/model.mjs');const p=JSON.parse(localStorage.getItem('ashenspire.pose-studio.draft.v1'));return sample(p,Number(document.querySelector('#scrub').value)).effects.some(c=>c.effect==='wardCatch');});assert.ok(visible,'Newly added effect must be visible at the playhead');
 await page.locator('[data-field="cue"]').selectOption('contact');const added=(await draft()).clips.at(-1);assert.equal(added.offset,0);assert.equal(added.cue,'contact');const rows=await page.locator('[data-layer="front"] .clip').all();assert.equal(rows.length,2);const first=await rows[0].boundingBox(),second=await rows[1].boundingBox();assert.ok(first.y+first.height<=second.y,'Overlapping effects need separate selectable rows');checks.push('adding an effect reveals it; choosing a moment resets old absolute timing');
 await page.locator('#effect-advanced > summary').click();await page.locator('[data-field="rotation"]').fill('25');await page.locator('[data-field="rotation"]').press('Tab');assert.equal(await page.locator('#effect-advanced').getAttribute('open'),'');checks.push('advanced controls stay expanded after edits');
 await page.locator('#effect-advanced > summary').click();await page.screenshot({path:path.join(out,'intuitive-desktop.png'),fullPage:true});
 const before=await draft();await page.locator('#connect-next').click();await page.locator('#card').selectOption('gorefireSlash');await page.locator('#connect-card').click();const after=await draft();assert.deepEqual(after.clips,before.clips);assert.deepEqual(after.poses,before.poses);assert.deepEqual(after.anchors,before.anchors);assert.equal(after.bindings[0].objectId,'gorefireSlash');assert.match(await page.locator('#resolution').textContent(),/Matched/);assert.equal(await page.locator('#rule-advanced').getAttribute('open'),null);checks.push('connect a real card without replacing the animation or exposing technical fields');
 await page.locator('[data-binding-field="name"]').fill('Paid ward');await page.locator('[data-binding-field="name"]').press('Tab');assert.ok(await page.evaluate(()=>document.activeElement.closest('#binding-form')));await page.locator('[data-binding-field="resource"]').selectOption('mana');await page.locator('#test-mana').fill('0');await page.locator('#test-stamina').fill('0');assert.ok(await page.locator('#preview-match').isDisabled());await page.locator('#test-mana').fill('1');assert.ok(await page.locator('#preview-match').isEnabled());await page.screenshot({path:path.join(out,'intuitive-connections.png'),fullPage:true});await page.locator('#preview-match').click();assert.equal(await page.locator('[data-tab="compose"]').getAttribute('aria-current'),'page');assert.match(await page.locator('#play').textContent(),/Pause/);await page.locator('#play').click();checks.push('connection feedback explains mismatches and previews only a matching rule');
 await page.setViewportSize({width:900,height:900});const mainWidth=(await page.locator('main').boundingBox()).width;await page.locator('#add-effect').tap();assert.equal((await page.locator('main').boundingBox()).width,mainWidth);await page.locator('#close-library').click();assert.ok(await page.locator('#library-dock').isHidden());checks.push('tablet library opens inline without changing canvas width');await page.setViewportSize({width:390,height:844});await page.locator('#add-effect').tap();assert.ok(await page.locator('#library-dock').isVisible());assert.equal(await page.locator('#tool-dialog').evaluate(el=>el.matches(':modal')),false);assert.equal(await page.locator('#library-title').evaluate(el=>el===document.activeElement),true);await page.keyboard.press('Escape');assert.ok(await page.locator('#library-dock').isHidden());assert.equal(await page.locator('#add-effect').evaluate(el=>el===document.activeElement),true);
 await page.locator('#add-effect').tap();await page.locator('#search').fill('heel');await page.locator('[data-effect="heelScuff"]').tap();await page.waitForFunction(()=>!document.querySelector('#tool-dialog').open);assert.match(await page.locator('#selection').textContent(),/Heel scuff/);assert.equal((await draft()).clips.at(-1).anchor,'feet');assert.equal(await page.locator('.library').count(),1);assert.ok(await page.locator('.workspace > .library').count());
 await page.locator('#edit-effect').click();if(await page.locator('#effect-advanced').getAttribute('open')===null)await page.locator('#effect-advanced > summary').click();await page.locator('[data-field="x"]').fill('35');await page.locator('[data-field="x"]').press('Tab');assert.equal((await draft()).clips.at(-1).x,35);assert.equal(await page.locator('#effect-advanced').getAttribute('open'),'');assert.ok(await page.evaluate(()=>document.activeElement.closest('#tool-dialog')));
 await page.screenshot({path:path.join(out,'intuitive-phone-controls.png'),fullPage:false});await page.locator('#close-tool').click();await page.waitForFunction(()=>!document.querySelector('#tool-dialog').open);assert.equal(await page.locator('#edit-effect').evaluate(el=>el===document.activeElement),true);assert.equal(await page.locator('.inspector').count(),1);checks.push('phone panels support touch selection, Escape, precise editing and focus return without duplicate controls');
 await page.locator('#stage').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'intuitive-phone.png'),fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));for(const selector of ['#add-effect','#edit-effect','#play','#forward']){const box=await page.locator(selector).boundingBox();assert.ok(box.width>=44&&box.height>=44,selector);}checks.push('390px layout contains content and primary touch targets are at least 44px');
 const final=await draft(),downloadEvent=page.waitForEvent('download');await page.locator('#save').click();const download=await downloadEvent;await download.saveAs(path.join(out,'intuitive.pose.json'));await page.reload();await page.locator('.clip').first().waitFor();assert.equal((await draft()).clips.at(-1).x,final.clips.at(-1).x);checks.push('download and reload preserve edits');
 assert.deepEqual(errors,[]);await writeFile(path.join(out,'usability-checks.json'),JSON.stringify({checks,errors},null,2));console.log(JSON.stringify({checks,errors},null,2));
}finally{await browser.close();}
