// src/content/aiDisclosure.js — THE ONE HOME of the AI-use acknowledgement.
//
// Two surfaces render from this file and neither retypes it:
//   · in-product  — Settings → About (src/ui/screens/about.js)
//   · the store   — Steam's AI-disclosure field, printed by
//                   `node tools/ai-disclosure.mjs` and pasted from that output
//
// WHY IT LIVES HERE AND NOT IN A DOCUMENT. The same acknowledgement appearing
// in two places, maintained by hand, is one fact with two homes: the day they
// disagree, a player comparing the store page to the game is reading two
// different claims about the same thing and we cannot say which is true.
// So the text has one home — this file — and everything else renders it.
// `node tools/ai-disclosure.mjs --check` fails if a shipped bundle has drifted
// from this module, which is what makes that a fact rather than an intention.
//
// APPROVAL: the final wording is Constantine's call at release (`approved`
// below). An edit here lands on both surfaces in the same act, which is the
// entire point of the arrangement.
//
// Headless-safe: data only, no document, no storage, no timers.

// The load-bearing sentence gets its own name because it has two jobs: it is the
// last line a player reads, and it is the claim `tools/ai-disclosure.mjs` proves.
// It used to exist twice — once here inside `storeForm`, once paraphrased in
// `runtimeCheck.claim` — in DIFFERENT WORDS, so no comparison could ever have
// caught them diverging, and the copy with no reader was the one that would rot
// (Bjorn found it at the pixel; nothing rendered it and `--check` never bound
// it). One home now: the falsifier and the player are told the same sentence,
// because it is the same string.
const RUNTIME_CLAIM = `No AI runs while you play: nothing in the game is AI-generated at runtime, and the game contacts no AI service.`;

// The rest of the store form. Kept a separate unbroken literal so `--check` can
// bind each piece in the shipped bundle; the bundler preserves source literals,
// and an interpolation would put the template — not the text — in the bundle.
const STORE_LEAD = `Ashen Spire was built by AI under human direction. The game’s code, design, writing, and art pipelines were authored by AI assistants (Anthropic’s Claude) working under the human developer’s instruction, review, and testing. Most shipped art is generated by that code — the game’s own placeholder renderer and AI-written 3D rendering pipelines. The four playable class figures are the exception, and were made by a different system: they were produced with an AI image-generation model (OpenAI’s ChatGPT Codex) and prepared for the game by AI-written tooling. The sound effects are synthesized by AI-written code at runtime, and the soundtrack was composed as code by AI: written note by note and rendered by an AI-written synthesizer, with no samples and no AI music model. Hosted builds play the rendered tracks; the game's own synthesized score stands in wherever they cannot load.`;

// THE `version` FIELD IS GONE, AND THE APPROVED WORDING BELOW IS UNTOUCHED.
//
// It held `'0.4.x'` — a hand-typed scope string, rendered on Settings → About
// while title/map/combat rendered the derived build stamp: two numbers on two
// screens, live. `tools/buildversion.mjs` row B had this listed as a second
// version site that was KNOWN AND OPEN, resolving the whole check to UNKNOWN,
// because which of the two should move was a Tier-2 call and Constantine's
// alone. He made it on 2026-08-16 — "a4 is really nice" — and A4 puts the
// derived build version on the About line. So the field has no reader left,
// and a value nobody renders is the copy this file's own header warns about.
//
// THIS IS NOT AN EDIT TO THE ACKNOWLEDGEMENT. `approved` guards the text below
// it — storeForm, sections, runtimeCheck — which is what he read and approved
// (b349bbd / #92). `version` sat above the flag, is not a word of the
// acknowledgement, and `tools/ai-disclosure.mjs --check` binds DISCLOSURE_PARTS
// (the store lead and the runtime claim), neither of which moves here. The flag
// stays `true` because the wording it is about is byte-identical.
//
// `updated` STAYS, AND IT STAYS HAND-TYPED. It is the date this wording last
// changed — a fact of the text's own history, not of the build — and nothing in
// this tree derives it. It is not made derived here rather than being given a
// plausible machine answer; see the session log.
export const AI_DISCLOSURE = Object.freeze({
  updated: '2026-09-26',

  // TRUE again since 2026-09-03, on the CORRECTED wording below.
  //
  // The history, because the flag means nothing without it:
  //
  // Approved 2026-08-07 — "I approve the ai disclosure." That wording said "no
  // AI image-generation models were used" and "No image-generation model was
  // used at any point". Both became FALSE when the four class figures were
  // replaced with art produced by ChatGPT Codex (AS-HD-040, owner statement
  // 2026-09-03). A disclosure that is wrong about the one thing it exists to
  // disclose is worse than no disclosure, so the wording was corrected and this
  // flag went to `false` — the rule stated here being that any edit returns it.
  //
  // It went to false a second time within the day: the first correction
  // attributed all art to Claude and then named ChatGPT Codex two sentences
  // later, which replaced a false claim with an inconsistent one. Narrowed to
  // "art PIPELINES" (Claude wrote the pipelines; the pipelines generate most of
  // the art; the four figures came from elsewhere).
  //
  // Constantine read and approved THAT wording — the text as it stands below —
  // on 2026-09-03. Approving it was his call and not the maker seat's; the flag
  // is set here on his instruction, not on this seat's judgement.
  //
  // WHAT BACKS IT, EXACTLY. His instruction in the working session, and nothing
  // else. There is no `.agentops` event recording it — and there never has been
  // for this flag: a search of the whole event tree returns ZERO events
  // mentioning this disclosure, including the 2026-08-07 approval that this one
  // replaces. The flag has been prose-authorised for its entire life. That is
  // stated here rather than left for a reader to discover, because "approved"
  // with no visible provenance is exactly the kind of marker that gets trusted
  // for more than it can carry.
  //
  // A request to record the decision through the control plane has gone to
  // it-manager-iii along with the ticket's other two governance items. If it is
  // recorded, cite the event here. Until then this line means "the owner said
  // yes", which is what it has always meant — no more.
  //
  // Scope, so it is not over-read: nothing in `src/` reads this flag, and
  // `tools/ai-disclosure.mjs` only PRINTS a note when it is false — it exits 0
  // either way. It gates a release by informing the person cutting one; it does
  // not gate a build, and this branch releases nothing.
  //
  // Nothing in the game reads this flag to decide whether to render — the
  // acknowledgement always shows. It marks whose words these are. Edit the text
  // below and it returns to `false`, same rule, no exceptions.
  //
  // RETURNED TO `false` ON 2026-09-24 (#1274), by that rule: the store lead, the
  // Audio section and the While-you-play section were edited to describe the
  // recorded music the hosted builds play: first ElevenLabs tracks, then, on
  // 2026-09-26, a score written as code that replaced them. The wording above
  // is the maker seat's until Constantine reads and approves it.
  approved: false,

  /**
   * storeForm — the text pasted into Steam's AI-disclosure field, and the lead
   * paragraph of the in-product acknowledgement. ONE string, both surfaces.
   */
  // Assembled from its two parts, so the claim below and the last sentence a
  // player reads are the same string rather than two sentences that agree today.
  storeForm: `${STORE_LEAD} ${RUNTIME_CLAIM}`,

  /**
   * sections — the fuller acknowledgement, shown under the lead in-product.
   * Each is one honest answer to "what did the AI actually do here".
   */
  sections: Object.freeze([
    Object.freeze({
      heading: 'Code and design',
      body: `The engine, interface, tools, and the design specification were written by AI assistants working as a team of specialist personas, under the direction of the human developer — who set the goals, reviewed the work, played the builds, and holds final approval on everything that ships.`,
    }),
    Object.freeze({
      heading: 'Writing',
      body: `All game text — card names and rules text, interface copy, flavour — was AI-authored under that same direction.`,
    }),
    Object.freeze({
      heading: 'Art',
      body: `Nearly every visual is generated by code. Sprites, icons and panels are drawn at runtime by the game itself; the enemy figures, act backdrops and equipment art are pre-rendered by procedural Blender scripts that the AI wrote. The four playable class figures are the one exception: they were produced with an AI image-generation model (ChatGPT Codex), then cut out and framed for the game by AI-written tooling. Every such file is listed in CREDITS with its source and licence.`,
    }),
    Object.freeze({
      heading: 'Audio',
      body: `Every sound effect is synthesized as you play by AI-written code. The music was composed as code by AI: each track is written as notes in music/score/ and rendered offline by an AI-written synthesizer, with no samples and no AI music model. A build served from the web plays those renders; a build opened from a file on disk, or any screen whose track cannot load, uses the game's live synthesized score instead.`,
    }),
    Object.freeze({
      heading: 'While you play',
      body: `No AI model runs in this game, on your machine or anywhere else. Nothing is generated while you play, and the game never contacts an AI service. The only network features are optional local co-op and loading music files: the rendered score beside the game, or an optional folder of your own.`,
    }),
    Object.freeze({
      heading: 'Your saves',
      body: `Your profile and runs are yours. When something cannot be read, it is set aside rather than deleted, and Profile on the title screen lists the copies still in the drawer — with a button to save any of them to a file. Profile copies are never deleted to make room. Run copies are kept for up to six months, with the newest 12 in the drawer.`,
    }),
  ]),

  /**
   * runtimeCheck — the load-bearing claim, and where its falsifier lives.
   *
   * THE COMMANDS ARE NOT IN THIS FILE, AND THAT IS DELIBERATE. This module is
   * the disclosure, so it necessarily names the AI vendor it is disclosing; and
   * a search pattern stored here would spell out every vendor and every
   * network-primitive name the pattern hunts for. Both times I tried it, our
   * own falsifier matched its own text and returned red on a clean tree —
   * first the vendor name in `storeForm`, then the pattern inside the pattern.
   * A falsifier that cannot survive being written down beside its claim belongs
   * one step away from it, outside `src/`, where what it searches cannot
   * contain it. (This comment is written the same way, on purpose: it describes
   * the trap without spelling the words that would spring it.)
   *
   * So: `tools/ai-disclosure.mjs` owns the commands, prints them verbatim
   * (`--evidence`) and runs them (`--check`). This file owns the claim.
   */
  runtimeCheck: Object.freeze({
    claim: RUNTIME_CLAIM,
    verifyWith: `node tools/ai-disclosure.mjs --evidence`,
    networkNote: `A separate grep for network primitives returns exactly two sites in the whole game, both local and neither AI: src/net/lan.js (LAN co-op against the game's own launcher) and src/ui/audio.js (the music folder: the player's own, or the shipped music/ beside the page).`,
  }),
});

/** The atomic texts the bundles must carry — each an unbroken literal above. */
export const DISCLOSURE_PARTS = Object.freeze([
  Object.freeze({ name: 'store lead', text: STORE_LEAD }),
  Object.freeze({ name: 'runtime claim (also runtimeCheck.claim)', text: RUNTIME_CLAIM }),
]);

/**
 * The in-product acknowledgement as plain text — the export/copy path.
 *
 * THE VERSION IS PASSED IN AND NOT IMPORTED, and that is load-bearing rather
 * than fussy. `tools/ai-disclosure.mjs --evidence` prints, as the falsifier a
 * sceptic pastes into a terminal, that this file "imports nothing and calls
 * nothing" — it is the command that closes the hole left by excluding this file
 * from the AI-service grep. An `import` here would make that evidence false.
 * So the caller, which already knows the build, hands the version down.
 */
export function disclosureAsText(d = AI_DISCLOSURE, version = null) {
  return [
    version ? `Ashen Spire — AI use acknowledgement (${version})` : `Ashen Spire — AI use acknowledgement`,
    '',
    d.storeForm,
    '',
    ...d.sections.map((s) => `${s.heading}\n${s.body}\n`),
  ].join('\n');
}
