// Generated by tools/combat-effects-ship.mjs and tools/card-effect-art-build.mjs. Six frames, center anchor, 256px canvas.
export const COMBAT_EFFECT_ART = {
  "starbolt": [
    "assets/combat-effects/starbolt1.webp",
    "assets/combat-effects/starbolt2.webp",
    "assets/combat-effects/starbolt3.webp",
    "assets/combat-effects/starbolt4.webp",
    "assets/combat-effects/starbolt5.webp",
    "assets/combat-effects/starbolt6.webp"
  ],
  "emberbolt": [
    "assets/combat-effects/emberbolt1.webp",
    "assets/combat-effects/emberbolt2.webp",
    "assets/combat-effects/emberbolt3.webp",
    "assets/combat-effects/emberbolt4.webp",
    "assets/combat-effects/emberbolt5.webp",
    "assets/combat-effects/emberbolt6.webp"
  ],
  "shadowbolt": [
    "assets/combat-effects/shadowbolt1.webp",
    "assets/combat-effects/shadowbolt2.webp",
    "assets/combat-effects/shadowbolt3.webp",
    "assets/combat-effects/shadowbolt4.webp",
    "assets/combat-effects/shadowbolt5.webp",
    "assets/combat-effects/shadowbolt6.webp"
  ],
  "sacredbolt": [
    "assets/combat-effects/sacredbolt1.webp",
    "assets/combat-effects/sacredbolt2.webp",
    "assets/combat-effects/sacredbolt3.webp",
    "assets/combat-effects/sacredbolt4.webp",
    "assets/combat-effects/sacredbolt5.webp",
    "assets/combat-effects/sacredbolt6.webp"
  ],
  "ward": [
    "assets/combat-effects/ward1.webp",
    "assets/combat-effects/ward2.webp",
    "assets/combat-effects/ward3.webp",
    "assets/combat-effects/ward4.webp",
    "assets/combat-effects/ward5.webp",
    "assets/combat-effects/ward6.webp"
  ],
  "gorefire": [
    "assets/combat-effects/gorefire1.webp",
    "assets/combat-effects/gorefire2.webp",
    "assets/combat-effects/gorefire3.webp",
    "assets/combat-effects/gorefire4.webp",
    "assets/combat-effects/gorefire5.webp",
    "assets/combat-effects/gorefire6.webp"
  ],
  "heal": [
    "assets/combat-effects/heal1.webp",
    "assets/combat-effects/heal2.webp",
    "assets/combat-effects/heal3.webp",
    "assets/combat-effects/heal4.webp",
    "assets/combat-effects/heal5.webp",
    "assets/combat-effects/heal6.webp"
  ],
  "impact": [
    "assets/combat-effects/impact1.webp",
    "assets/combat-effects/impact2.webp",
    "assets/combat-effects/impact3.webp",
    "assets/combat-effects/impact4.webp",
    "assets/combat-effects/impact5.webp",
    "assets/combat-effects/impact6.webp"
  ],
  "slash": [
    "assets/combat-effects/slash1.webp",
    "assets/combat-effects/slash2.webp",
    "assets/combat-effects/slash3.webp",
    "assets/combat-effects/slash4.webp",
    "assets/combat-effects/slash5.webp",
    "assets/combat-effects/slash6.webp"
  ],
  "thrust": [
    "assets/combat-effects/thrust1.webp",
    "assets/combat-effects/thrust2.webp",
    "assets/combat-effects/thrust3.webp",
    "assets/combat-effects/thrust4.webp",
    "assets/combat-effects/thrust5.webp",
    "assets/combat-effects/thrust6.webp"
  ],
  "heavyImpact": [
    "assets/combat-effects/heavyImpact1.webp",
    "assets/combat-effects/heavyImpact2.webp",
    "assets/combat-effects/heavyImpact3.webp",
    "assets/combat-effects/heavyImpact4.webp",
    "assets/combat-effects/heavyImpact5.webp",
    "assets/combat-effects/heavyImpact6.webp"
  ],
  "bloodSlash": [
    "assets/combat-effects/bloodSlash1.webp",
    "assets/combat-effects/bloodSlash2.webp",
    "assets/combat-effects/bloodSlash3.webp",
    "assets/combat-effects/bloodSlash4.webp",
    "assets/combat-effects/bloodSlash5.webp",
    "assets/combat-effects/bloodSlash6.webp"
  ],
  "venom": [
    "assets/combat-effects/venom1.webp",
    "assets/combat-effects/venom2.webp",
    "assets/combat-effects/venom3.webp",
    "assets/combat-effects/venom4.webp",
    "assets/combat-effects/venom5.webp",
    "assets/combat-effects/venom6.webp"
  ],
  "blight": [
    "assets/combat-effects/blight1.webp",
    "assets/combat-effects/blight2.webp",
    "assets/combat-effects/blight3.webp",
    "assets/combat-effects/blight4.webp",
    "assets/combat-effects/blight5.webp",
    "assets/combat-effects/blight6.webp"
  ],
  "ash": [
    "assets/combat-effects/ash1.webp",
    "assets/combat-effects/ash2.webp",
    "assets/combat-effects/ash3.webp",
    "assets/combat-effects/ash4.webp",
    "assets/combat-effects/ash5.webp",
    "assets/combat-effects/ash6.webp"
  ],
  "ritual": [
    "assets/combat-effects/ritual1.webp",
    "assets/combat-effects/ritual2.webp",
    "assets/combat-effects/ritual3.webp",
    "assets/combat-effects/ritual4.webp",
    "assets/combat-effects/ritual5.webp",
    "assets/combat-effects/ritual6.webp"
  ],
  "shieldBash": [
    "assets/combat-effects/shieldBash1.webp",
    "assets/combat-effects/shieldBash2.webp",
    "assets/combat-effects/shieldBash3.webp",
    "assets/combat-effects/shieldBash4.webp",
    "assets/combat-effects/shieldBash5.webp",
    "assets/combat-effects/shieldBash6.webp"
  ],
  "parry": [
    "assets/combat-effects/parry1.webp",
    "assets/combat-effects/parry2.webp",
    "assets/combat-effects/parry3.webp",
    "assets/combat-effects/parry4.webp",
    "assets/combat-effects/parry5.webp",
    "assets/combat-effects/parry6.webp"
  ],
  "crossSlash": [
    "assets/combat-effects/crossSlash1.webp",
    "assets/combat-effects/crossSlash2.webp",
    "assets/combat-effects/crossSlash3.webp",
    "assets/combat-effects/crossSlash4.webp",
    "assets/combat-effects/crossSlash5.webp",
    "assets/combat-effects/crossSlash6.webp"
  ],
  "whirlwind": [
    "assets/combat-effects/whirlwind1.webp",
    "assets/combat-effects/whirlwind2.webp",
    "assets/combat-effects/whirlwind3.webp",
    "assets/combat-effects/whirlwind4.webp",
    "assets/combat-effects/whirlwind5.webp",
    "assets/combat-effects/whirlwind6.webp"
  ],
  "lifeDrain": [
    "assets/combat-effects/lifeDrain1.webp",
    "assets/combat-effects/lifeDrain2.webp",
    "assets/combat-effects/lifeDrain3.webp",
    "assets/combat-effects/lifeDrain4.webp",
    "assets/combat-effects/lifeDrain5.webp",
    "assets/combat-effects/lifeDrain6.webp"
  ],
  "cleanse": [
    "assets/combat-effects/cleanse1.webp",
    "assets/combat-effects/cleanse2.webp",
    "assets/combat-effects/cleanse3.webp",
    "assets/combat-effects/cleanse4.webp",
    "assets/combat-effects/cleanse5.webp",
    "assets/combat-effects/cleanse6.webp"
  ],
  "arcaneBurst": [
    "assets/combat-effects/arcaneBurst1.webp",
    "assets/combat-effects/arcaneBurst2.webp",
    "assets/combat-effects/arcaneBurst3.webp",
    "assets/combat-effects/arcaneBurst4.webp",
    "assets/combat-effects/arcaneBurst5.webp",
    "assets/combat-effects/arcaneBurst6.webp"
  ],
  "bind": [
    "assets/combat-effects/bind1.webp",
    "assets/combat-effects/bind2.webp",
    "assets/combat-effects/bind3.webp",
    "assets/combat-effects/bind4.webp",
    "assets/combat-effects/bind5.webp",
    "assets/combat-effects/bind6.webp"
  ],
  "steelGlint": [
    "assets/combat-effects/steelGlint1.webp",
    "assets/combat-effects/steelGlint2.webp",
    "assets/combat-effects/steelGlint3.webp",
    "assets/combat-effects/steelGlint4.webp",
    "assets/combat-effects/steelGlint5.webp",
    "assets/combat-effects/steelGlint6.webp"
  ],
  "dustStep": [
    "assets/combat-effects/dustStep1.webp",
    "assets/combat-effects/dustStep2.webp",
    "assets/combat-effects/dustStep3.webp",
    "assets/combat-effects/dustStep4.webp",
    "assets/combat-effects/dustStep5.webp",
    "assets/combat-effects/dustStep6.webp"
  ],
  "focusMotes": [
    "assets/combat-effects/focusMotes1.webp",
    "assets/combat-effects/focusMotes2.webp",
    "assets/combat-effects/focusMotes3.webp",
    "assets/combat-effects/focusMotes4.webp",
    "assets/combat-effects/focusMotes5.webp",
    "assets/combat-effects/focusMotes6.webp"
  ],
  "guardPulse": [
    "assets/combat-effects/guardPulse1.webp",
    "assets/combat-effects/guardPulse2.webp",
    "assets/combat-effects/guardPulse3.webp",
    "assets/combat-effects/guardPulse4.webp",
    "assets/combat-effects/guardPulse5.webp",
    "assets/combat-effects/guardPulse6.webp"
  ],
  "physicalGuard": [
    "assets/combat-effects/physicalGuard1.webp",
    "assets/combat-effects/physicalGuard2.webp",
    "assets/combat-effects/physicalGuard3.webp",
    "assets/combat-effects/physicalGuard4.webp",
    "assets/combat-effects/physicalGuard5.webp",
    "assets/combat-effects/physicalGuard6.webp"
  ],
  "arcaneWard": [
    "assets/combat-effects/arcaneWard1.webp",
    "assets/combat-effects/arcaneWard2.webp",
    "assets/combat-effects/arcaneWard3.webp",
    "assets/combat-effects/arcaneWard4.webp",
    "assets/combat-effects/arcaneWard5.webp",
    "assets/combat-effects/arcaneWard6.webp"
  ],
  "magicGuard": [
    "assets/combat-effects/magicGuard1.webp",
    "assets/combat-effects/magicGuard2.webp",
    "assets/combat-effects/magicGuard3.webp",
    "assets/combat-effects/magicGuard4.webp",
    "assets/combat-effects/magicGuard5.webp",
    "assets/combat-effects/magicGuard6.webp"
  ],
  "barrier": [
    "assets/combat-effects/barrier1.webp",
    "assets/combat-effects/barrier2.webp",
    "assets/combat-effects/barrier3.webp",
    "assets/combat-effects/barrier4.webp",
    "assets/combat-effects/barrier5.webp",
    "assets/combat-effects/barrier6.webp"
  ],
  "bulwarkStance": [
    "assets/combat-effects/bulwarkStance1.webp",
    "assets/combat-effects/bulwarkStance2.webp",
    "assets/combat-effects/bulwarkStance3.webp",
    "assets/combat-effects/bulwarkStance4.webp",
    "assets/combat-effects/bulwarkStance5.webp",
    "assets/combat-effects/bulwarkStance6.webp"
  ],
  "duelistStance": [
    "assets/combat-effects/duelistStance1.webp",
    "assets/combat-effects/duelistStance2.webp",
    "assets/combat-effects/duelistStance3.webp",
    "assets/combat-effects/duelistStance4.webp",
    "assets/combat-effects/duelistStance5.webp",
    "assets/combat-effects/duelistStance6.webp"
  ],
  "channelStance": [
    "assets/combat-effects/channelStance1.webp",
    "assets/combat-effects/channelStance2.webp",
    "assets/combat-effects/channelStance3.webp",
    "assets/combat-effects/channelStance4.webp",
    "assets/combat-effects/channelStance5.webp",
    "assets/combat-effects/channelStance6.webp"
  ],
  "berserkStance": [
    "assets/combat-effects/berserkStance1.webp",
    "assets/combat-effects/berserkStance2.webp",
    "assets/combat-effects/berserkStance3.webp",
    "assets/combat-effects/berserkStance4.webp",
    "assets/combat-effects/berserkStance5.webp",
    "assets/combat-effects/berserkStance6.webp"
  ],
  "bloodAura": [
    "assets/combat-effects/bloodAura1.webp",
    "assets/combat-effects/bloodAura2.webp",
    "assets/combat-effects/bloodAura3.webp",
    "assets/combat-effects/bloodAura4.webp",
    "assets/combat-effects/bloodAura5.webp",
    "assets/combat-effects/bloodAura6.webp"
  ],
  "frostAura": [
    "assets/combat-effects/frostAura1.webp",
    "assets/combat-effects/frostAura2.webp",
    "assets/combat-effects/frostAura3.webp",
    "assets/combat-effects/frostAura4.webp",
    "assets/combat-effects/frostAura5.webp",
    "assets/combat-effects/frostAura6.webp"
  ],
  "poisonAura": [
    "assets/combat-effects/poisonAura1.webp",
    "assets/combat-effects/poisonAura2.webp",
    "assets/combat-effects/poisonAura3.webp",
    "assets/combat-effects/poisonAura4.webp",
    "assets/combat-effects/poisonAura5.webp",
    "assets/combat-effects/poisonAura6.webp"
  ],
  "sacredAura": [
    "assets/combat-effects/sacredAura1.webp",
    "assets/combat-effects/sacredAura2.webp",
    "assets/combat-effects/sacredAura3.webp",
    "assets/combat-effects/sacredAura4.webp",
    "assets/combat-effects/sacredAura5.webp",
    "assets/combat-effects/sacredAura6.webp"
  ],
  "bloodLoss": [
    "assets/combat-effects/bloodLoss1.webp",
    "assets/combat-effects/bloodLoss2.webp",
    "assets/combat-effects/bloodLoss3.webp",
    "assets/combat-effects/bloodLoss4.webp",
    "assets/combat-effects/bloodLoss5.webp",
    "assets/combat-effects/bloodLoss6.webp"
  ],
  "frostbite": [
    "assets/combat-effects/frostbite1.webp",
    "assets/combat-effects/frostbite2.webp",
    "assets/combat-effects/frostbite3.webp",
    "assets/combat-effects/frostbite4.webp",
    "assets/combat-effects/frostbite5.webp",
    "assets/combat-effects/frostbite6.webp"
  ],
  "poisoned": [
    "assets/combat-effects/poisoned1.webp",
    "assets/combat-effects/poisoned2.webp",
    "assets/combat-effects/poisoned3.webp",
    "assets/combat-effects/poisoned4.webp",
    "assets/combat-effects/poisoned5.webp",
    "assets/combat-effects/poisoned6.webp"
  ],
  "staggerBreak": [
    "assets/combat-effects/staggerBreak1.webp",
    "assets/combat-effects/staggerBreak2.webp",
    "assets/combat-effects/staggerBreak3.webp",
    "assets/combat-effects/staggerBreak4.webp",
    "assets/combat-effects/staggerBreak5.webp",
    "assets/combat-effects/staggerBreak6.webp"
  ],
  "insanity": [
    "assets/combat-effects/insanity1.webp",
    "assets/combat-effects/insanity2.webp",
    "assets/combat-effects/insanity3.webp",
    "assets/combat-effects/insanity4.webp",
    "assets/combat-effects/insanity5.webp",
    "assets/combat-effects/insanity6.webp"
  ],
  "crimsonBlight": [
    "assets/combat-effects/crimsonBlight1.webp",
    "assets/combat-effects/crimsonBlight2.webp",
    "assets/combat-effects/crimsonBlight3.webp",
    "assets/combat-effects/crimsonBlight4.webp",
    "assets/combat-effects/crimsonBlight5.webp",
    "assets/combat-effects/crimsonBlight6.webp"
  ],
  "weak": [
    "assets/combat-effects/weak1.webp",
    "assets/combat-effects/weak2.webp",
    "assets/combat-effects/weak3.webp",
    "assets/combat-effects/weak4.webp",
    "assets/combat-effects/weak5.webp",
    "assets/combat-effects/weak6.webp"
  ],
  "vulnerable": [
    "assets/combat-effects/vulnerable1.webp",
    "assets/combat-effects/vulnerable2.webp",
    "assets/combat-effects/vulnerable3.webp",
    "assets/combat-effects/vulnerable4.webp",
    "assets/combat-effects/vulnerable5.webp",
    "assets/combat-effects/vulnerable6.webp"
  ],
  "frail": [
    "assets/combat-effects/frail1.webp",
    "assets/combat-effects/frail2.webp",
    "assets/combat-effects/frail3.webp",
    "assets/combat-effects/frail4.webp",
    "assets/combat-effects/frail5.webp",
    "assets/combat-effects/frail6.webp"
  ],
  "dodge": [
    "assets/combat-effects/dodge1.webp",
    "assets/combat-effects/dodge2.webp",
    "assets/combat-effects/dodge3.webp",
    "assets/combat-effects/dodge4.webp",
    "assets/combat-effects/dodge5.webp",
    "assets/combat-effects/dodge6.webp"
  ],
  "riposte": [
    "assets/combat-effects/riposte1.webp",
    "assets/combat-effects/riposte2.webp",
    "assets/combat-effects/riposte3.webp",
    "assets/combat-effects/riposte4.webp",
    "assets/combat-effects/riposte5.webp",
    "assets/combat-effects/riposte6.webp"
  ],
  "resist": [
    "assets/combat-effects/resist1.webp",
    "assets/combat-effects/resist2.webp",
    "assets/combat-effects/resist3.webp",
    "assets/combat-effects/resist4.webp",
    "assets/combat-effects/resist5.webp",
    "assets/combat-effects/resist6.webp"
  ],
  "barrierHit": [
    "assets/combat-effects/barrierHit1.webp",
    "assets/combat-effects/barrierHit2.webp",
    "assets/combat-effects/barrierHit3.webp",
    "assets/combat-effects/barrierHit4.webp",
    "assets/combat-effects/barrierHit5.webp",
    "assets/combat-effects/barrierHit6.webp"
  ],
  "barrierBreak": [
    "assets/combat-effects/barrierBreak1.webp",
    "assets/combat-effects/barrierBreak2.webp",
    "assets/combat-effects/barrierBreak3.webp",
    "assets/combat-effects/barrierBreak4.webp",
    "assets/combat-effects/barrierBreak5.webp",
    "assets/combat-effects/barrierBreak6.webp"
  ],
  "strength": [
    "assets/combat-effects/strength1.webp",
    "assets/combat-effects/strength2.webp",
    "assets/combat-effects/strength3.webp",
    "assets/combat-effects/strength4.webp",
    "assets/combat-effects/strength5.webp",
    "assets/combat-effects/strength6.webp"
  ],
  "dexterity": [
    "assets/combat-effects/dexterity1.webp",
    "assets/combat-effects/dexterity2.webp",
    "assets/combat-effects/dexterity3.webp",
    "assets/combat-effects/dexterity4.webp",
    "assets/combat-effects/dexterity5.webp",
    "assets/combat-effects/dexterity6.webp"
  ]
};
