// src/content/flasks.js — the M2 flask set (SPEC §5.5)
//
// 3 slots; found from combats (decaying drop chance, balance.rewards),
// shops, and events. Wondrous Draught is the repo's first — and only —
// scripts.js user (see scripts.js for the justification).

export const flasks = [
  {
    id: 'crimsonFlask',
    name: 'Crimson Flask',
    rarity: 'common',
    icon: '🧪',
    artKey: 'flask-crimson',
    artAsset: 'assets/ui/flasks/flask-crimson.webp',
    tint: '#ef7272',
    effects: [{ op: 'heal', target: 'self', amount: { f: 'percentMaxHp', of: 'self', pct: 25 } }],
    textTemplate: 'Heal 25% of your max HP.',
  },
  {
    id: 'azureFlask',
    name: 'Azure Flask',
    rarity: 'common',
    icon: '🫙',
    artKey: 'flask-azure',
    artAsset: 'assets/ui/flasks/flask-azure.webp',
    tint: '#75a9ff',
    effects: [{ op: 'restoreMana', amount: 1 }],
    textTemplate: 'Restore 1 Mana.',
  },
  {
    id: 'flaskOfFerocity',
    name: 'Flask of Ferocity',
    rarity: 'common',
    icon: '🍶',
    artKey: 'flask-ferocity',
    tint: '#d77b35',
    effects: [{ op: 'applyStatus', target: 'self', status: 'strength', stacks: 2 }],
    textTemplate: 'Gain 2 Strength this combat.',
  },
  {
    id: 'flaskOfStone',
    name: 'Flask of Stone',
    rarity: 'common',
    icon: '🏺',
    artKey: 'flask-stone',
    tint: '#9a8b73',
    effects: [{ op: 'block', target: 'self', amount: 15 }],
    textTemplate: 'Gain 15 Block.',
  },
  {
    id: 'blightCoating',
    name: 'Blight Coating',
    rarity: 'uncommon',
    icon: '🦠',
    artKey: 'flask-blight',
    tint: '#73984d',
    targeted: true,
    effects: [{ op: 'applyStatus', target: 'enemy', status: 'crimsonBlight', stacks: 4 }],
    textTemplate: 'Apply 4 Crimson Blight to an enemy.',
  },
  {
    id: 'bloodUnction',
    name: 'Blood Unction',
    rarity: 'uncommon',
    icon: '🫗',
    artKey: 'flask-blood',
    tint: '#8e3143',
    effects: [{ op: 'applyStatus', target: 'self', status: 'bloodUnction', stacks: 1 }],
    textTemplate: 'This turn, your attacks apply 2 extra Bleed per hit.',
  },
  {
    id: 'wondrousDraught',
    name: 'Wondrous Draught',
    rarity: 'rare',
    icon: '⚗',
    artKey: 'flask-wondrous',
    tint: '#9a65c7',
    effects: [{ script: 'wondrousDraught' }],
    textTemplate: 'Gain the effects of two different random flasks at once.',
  },
];
