// Generated by tools/readiness-poses-ship.mjs.
export const READINESS_POSE_ART = {
  "rogue": {
    "prepared": {
      "file": "assets/readiness-poses/rogue/prepared.webp",
      "box": {
        "x0": 150,
        "y0": 324,
        "x1": 490,
        "y1": 600
      }
    },
    "preparedTransition": {
      "file": "assets/readiness-poses/rogue/preparedTransition.webp",
      "box": {
        "x0": 180,
        "y0": 324,
        "x1": 459,
        "y1": 600
      }
    }
  },
  "rogue-duelist": {
    "prepared": {
      "file": "assets/readiness-poses/rogue-duelist/prepared.webp",
      "box": {
        "x0": 138,
        "y0": 317,
        "x1": 502,
        "y1": 600
      }
    },
    "preparedTransition": {
      "file": "assets/readiness-poses/rogue-duelist/preparedTransition.webp",
      "box": {
        "x0": 178,
        "y0": 317,
        "x1": 462,
        "y1": 600
      }
    }
  },
  "rogue-nightveil": {
    "prepared": {
      "file": "assets/readiness-poses/rogue-nightveil/prepared.webp",
      "box": {
        "x0": 133,
        "y0": 291,
        "x1": 506,
        "y1": 600
      }
    },
    "preparedTransition": {
      "file": "assets/readiness-poses/rogue-nightveil/preparedTransition.webp",
      "box": {
        "x0": 165,
        "y0": 291,
        "x1": 474,
        "y1": 600
      }
    }
  },
  "rogue-shadow": {
    "prepared": {
      "file": "assets/readiness-poses/rogue-shadow/prepared.webp",
      "box": {
        "x0": 140,
        "y0": 305,
        "x1": 500,
        "y1": 600
      }
    },
    "preparedTransition": {
      "file": "assets/readiness-poses/rogue-shadow/preparedTransition.webp",
      "box": {
        "x0": 173,
        "y0": 305,
        "x1": 467,
        "y1": 600
      }
    }
  },
  "starseer": {
    "starstoneCharge": {
      "file": "assets/readiness-poses/starseer/starstoneCharge.webp",
      "box": {
        "x0": 174,
        "y0": 205,
        "x1": 465,
        "y1": 600
      }
    },
    "starstoneChargeTransition": {
      "file": "assets/readiness-poses/starseer/starstoneChargeTransition.webp",
      "box": {
        "x0": 177,
        "y0": 260,
        "x1": 462,
        "y1": 600
      }
    }
  },
  "starseer-astral": {
    "starstoneCharge": {
      "file": "assets/readiness-poses/starseer-astral/starstoneCharge.webp",
      "box": {
        "x0": 176,
        "y0": 205,
        "x1": 464,
        "y1": 600
      }
    },
    "starstoneChargeTransition": {
      "file": "assets/readiness-poses/starseer-astral/starstoneChargeTransition.webp",
      "box": {
        "x0": 176,
        "y0": 260,
        "x1": 464,
        "y1": 600
      }
    }
  },
  "starseer-eclipse": {
    "starstoneCharge": {
      "file": "assets/readiness-poses/starseer-eclipse/starstoneCharge.webp",
      "box": {
        "x0": 180,
        "y0": 205,
        "x1": 460,
        "y1": 600
      }
    },
    "starstoneChargeTransition": {
      "file": "assets/readiness-poses/starseer-eclipse/starstoneChargeTransition.webp",
      "box": {
        "x0": 182,
        "y0": 260,
        "x1": 458,
        "y1": 600
      }
    }
  },
  "starseer-starlit": {
    "starstoneCharge": {
      "file": "assets/readiness-poses/starseer-starlit/starstoneCharge.webp",
      "box": {
        "x0": 168,
        "y0": 207,
        "x1": 471,
        "y1": 600
      }
    },
    "starstoneChargeTransition": {
      "file": "assets/readiness-poses/starseer-starlit/starstoneChargeTransition.webp",
      "box": {
        "x0": 177,
        "y0": 261,
        "x1": 462,
        "y1": 600
      }
    }
  },
  "herald": {
    "bloodRite": {
      "file": "assets/readiness-poses/herald/bloodRite.webp",
      "box": {
        "x0": 199,
        "y0": 260,
        "x1": 441,
        "y1": 600
      }
    },
    "bloodRiteTransition": {
      "file": "assets/readiness-poses/herald/bloodRiteTransition.webp",
      "box": {
        "x0": 210,
        "y0": 260,
        "x1": 430,
        "y1": 600
      }
    }
  },
  "herald-emberhabit": {
    "bloodRite": {
      "file": "assets/readiness-poses/herald-emberhabit/bloodRite.webp",
      "box": {
        "x0": 194,
        "y0": 261,
        "x1": 446,
        "y1": 600
      }
    },
    "bloodRiteTransition": {
      "file": "assets/readiness-poses/herald-emberhabit/bloodRiteTransition.webp",
      "box": {
        "x0": 208,
        "y0": 261,
        "x1": 431,
        "y1": 600
      }
    }
  },
  "herald-ossuary": {
    "bloodRite": {
      "file": "assets/readiness-poses/herald-ossuary/bloodRite.webp",
      "box": {
        "x0": 200,
        "y0": 260,
        "x1": 440,
        "y1": 600
      }
    },
    "bloodRiteTransition": {
      "file": "assets/readiness-poses/herald-ossuary/bloodRiteTransition.webp",
      "box": {
        "x0": 211,
        "y0": 260,
        "x1": 429,
        "y1": 600
      }
    }
  },
  "herald-pilgrim": {
    "bloodRite": {
      "file": "assets/readiness-poses/herald-pilgrim/bloodRite.webp",
      "box": {
        "x0": 198,
        "y0": 261,
        "x1": 442,
        "y1": 600
      }
    },
    "bloodRiteTransition": {
      "file": "assets/readiness-poses/herald-pilgrim/bloodRiteTransition.webp",
      "box": {
        "x0": 206,
        "y0": 261,
        "x1": 434,
        "y1": 600
      }
    }
  }
};
