import {readFileSync,writeFileSync,mkdirSync,existsSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
import {createRequire} from 'node:module';
import {decodePng,encodePng,contentBox,resample} from '../../tools/concept-cutout.mjs';
import {ENEMY_POSES} from '../../src/content/enemyArt.js';
import {PAINTED_OUTFITS} from '../../src/content/paintedOutfits.js';
const require=createRequire(import.meta.url);let sharp;try{sharp=require('sharp')}catch{sharp=require('../../build/animation-tools/node_modules/sharp')}
const all=[...ENEMY_POSES,...Object.keys(PAINTED_OUTFITS)],selected=process.argv.slice(2),ids=selected.length?selected:all;
const metadataPath='asset-data/defeated-poses/manifest.json';
const entries=existsSync(metadataPath)?JSON.parse(readFileSync(metadataPath)).entries:{};
mkdirSync('assets/defeated-poses',{recursive:true});
for(const id of ids){
 const out=`art/defeated-poses/work/${id}`;mkdirSync(out,{recursive:true});
 const source=`art/defeated-poses/sheets/${id}.png`;
 execFileSync(process.execPath,['tools/painted-poses.mjs','--sheet',source,'--class',id,'--out',out,'--mask-only','--checker-pockets','--tolerance','75','--speck',id==='fellWarden'?'0.0003':'0.00004'],{stdio:'pipe'});
 const sheet=decodePng(readFileSync(`${out}/${id}_mask.png`));
 let split=Math.floor(sheet.width/2),best=Infinity;
 for(let x=Math.floor(sheet.width*.44);x<sheet.width*.56;x++){
  let ink=0;for(let y=0;y<sheet.height;y++)if(sheet.px[(y*sheet.width+x)*4+3]>40)ink++;
  const score=ink*10000+Math.abs(x-sheet.width/2);if(score<best){best=score;split=x;}
 }
 const images=[[0,split],[split,sheet.width]].map(([a,b])=>{
  const width=b-a,px=Buffer.alloc(width*sheet.height*4);
  for(let y=0;y<sheet.height;y++)sheet.px.copy(px,y*width*4,(y*sheet.width+a)*4,(y*sheet.width+b)*4);
  const img={width,height:sheet.height,bpp:4,px};return{img,box:contentBox(img)};
 });
 const scale=Math.min(...images.map(({box:b})=>Math.min(348/(b.x1-b.x0+1),344/(b.y1-b.y0+1))));
 const seedHeight=(images[0].box.y1-images[0].box.y0+1)*scale;
 const enemy=ENEMY_POSES.includes(id);
 const oldHeight=enemy?(()=>{const b=contentBox(decodePng(readFileSync(`assets/enemy-poses/${id}_idle.png`)));return b.y1-b.y0+1})():384;
 entries[id]={file:`assets/defeated-poses/${id}.webp`,scale:Number((oldHeight/seedHeight).toFixed(5)),kind:enemy?'enemy':'player'};
 for(let i=0;i<2;i++){
  const {img,box:b}=images[i],w=b.x1-b.x0+1,h=b.y1-b.y0+1,dw=Math.round(w*scale),dh=Math.round(h*scale);
  const small=resample(img,b.x0,b.y0,w,h,dw,dh),px=Buffer.alloc(384*384*4),left=Math.round((384-dw)/2),top=365-dh;
  for(let y=0;y<dh;y++)small.px.copy(px,((top+y)*384+left)*4,y*dw*4,(y+1)*dw*4);
  const png=encodePng(384,384,px);writeFileSync(`${out}/${i?'defeated':'seed'}.png`,png);
  if(i)await sharp(png).webp({quality:90,alphaQuality:100}).toFile(entries[id].file);
 }
 console.log(`${id}: defeated pose exported`);
}
mkdirSync('asset-data/defeated-poses',{recursive:true});writeFileSync(metadataPath,JSON.stringify({canvas:384,ground:364,entries},null,2)+'\n');
writeFileSync('src/content/defeatedArt.js','// Generated by art/defeated-poses/build.mjs.\nexport const DEFEATED_ART = '+JSON.stringify(entries,null,2)+';\n');
