#!/usr/bin/env node
// tools/parchment.mjs — writes the act plates: `assets/map/parchment_actN.svg`.
//
// WHAT THIS EXISTS FOR. Under the fog the unlit ground is most of the screen —
// at the entrance it is ALL of it but two circles — and Constantine asked for
// Elden Ring's undiscovered map. What reached his phone was a flat wash: no
// paper, no grain, no border. The plate the code binds by name,
// `assets/map/parchment_act1.webp`, HAS NEVER EXISTED. Not a broken image, not
// a console error, not a failing check: a 404 the screen renders as "fine, just
// flat", which is the most expensive kind of missing thing.
//
// GENERATED, BECAUSE THE CONSTRAINT IS HIS: "no billing, keep everything free."
// No paid plate, no CDN, no service. feTurbulence is free, deterministic, about
// two kilobytes, and it is the one texture generator every browser already
// ships.
//
// AND IT IS NOT DERIVED FROM THE GRAPH — that refusal is uiContent.js's and it
// still stands. Art derived from `mapgen` couples the flavour layer to a knob
// Constantine turns himself: he shortens a run with `floors` and the paper
// changes under him, which is Law 0 clause 5's silent-plausible-derivation. The
// only input here is the plate INDEX. Same index, same bytes, forever.
//
// THE PLATE CARRIES NO COLOUR, ON PURPOSE. `--fog-parchment` in styles/map.css
// is the one home for the per-act tone and the wash rect beneath already reads
// it. A plate with its own base colour would be a second copy of that datum,
// agreeing today and drifting the first time anyone tunes one of them (Law 1
// clause 2). So these are pure grey texture and the tone comes through them.
//
// WHY .svg AND NOT .webp. Because the file has to EXIST, and this is the medium
// this repo can generate for nothing. The extension has one home —
// `PARCHMENT_EXT` in src/ui/uiContent.js — and the convention is otherwise
// untouched, so when Freja's authored plates land she overwrites these three
// files (or flips one token) and nothing else in the tree moves.
//
// Usage
//   node tools/parchment.mjs            write every plate
//   node tools/parchment.mjs --check    exit 1 if any plate is missing or stale
//
// BOUNDARY: this writes files. It says nothing about whether the result LOOKS
// like paper on a phone — that is eyes, and mine are the ones that signed off on
// the shot in the log. It is silent on the bundle (tools/bundle.mjs sweeps
// assets/ wholesale and `.svg` is in its MIME table) and on whether anything
// still points at the old `.webp` (tests/engine.test.js, the act-plate test).

import { mkdirSync, writeFileSync, readFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { PARCHMENT_ACTS, PARCHMENT_EXT, parchmentAsset } from '../src/ui/uiContent.js';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const CHECK = process.argv.includes('--check');

// The plate is authored LARGE and drawn with `preserveAspectRatio="slice"`, so
// on every canvas the map actually reaches it is scaled DOWN and the grain
// stays fine. Measured at the shipping zoom: the entrance canvas is 433x1259
// SVG units and the widest mid-climb one 818x1448 — both inside this.
const W = 1024;
const H = 2048;

/**
 * One plate, from its index alone.
 *
 * THREE SCALES, because that is what makes a surface read as paper rather than
 * as noise: blotches you see across the room, fibres you see at arm's length,
 * grain you see up close. Each is one feTurbulence with a seed derived from the
 * plate index, so plate 2 is a different sheet of the same stock and not a
 * different material.
 */
function plate(i) {
  const seed = i * 97;
  const f = (id, freq, octaves, s) =>
    `<filter id="${id}" x="0" y="0" width="100%" height="100%" color-interpolation-filters="sRGB" filterUnits="objectBoundingBox">`
    + `<feTurbulence type="fractalNoise" baseFrequency="${freq}" numOctaves="${octaves}" seed="${s}" stitchTiles="stitch"/>`
    + `<feColorMatrix type="saturate" values="0"/>`
    + `</filter>`;
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="${W}" height="${H}" preserveAspectRatio="xMidYMid slice">
<title>Act plate ${i} — undiscovered ground. Generated by tools/parchment.mjs; do not hand-edit.</title>
<defs>
${f('blotch', '0.0016', 4, seed)}
${f('fibre', '0.004 0.28', 3, seed + 1)}
${f('grain', '0.85', 4, seed + 2)}
</defs>
<rect width="${W}" height="${H}" fill="#808080"/>
<rect width="${W}" height="${H}" filter="url(#blotch)" opacity="0.62"/>
<rect width="${W}" height="${H}" filter="url(#fibre)" opacity="0.24"/>
<rect width="${W}" height="${H}" filter="url(#grain)" opacity="0.30"/>
</svg>
`;
}

// The COUNT is data (`balance.ui.parchmentActs`) and the PATH is the same
// function the screen calls, so this loop cannot write a file the game will not
// look for, and a fourth act plate is a number in a table.
const wrote = [];
const stale = [];
mkdirSync(resolve(ROOT, 'assets/map'), { recursive: true });
for (let i = 1; i <= PARCHMENT_ACTS; i++) {
  // parchmentAsset takes an ACT number and resolves it to a plate; act i maps to
  // plate i for i <= PARCHMENT_ACTS, which is the whole set.
  const rel = parchmentAsset(i);
  const abs = resolve(ROOT, rel);
  const want = plate(i);
  const have = existsSync(abs) ? readFileSync(abs, 'utf8') : null;
  if (have === want) continue;
  if (CHECK) { stale.push(`${rel} — ${have == null ? 'MISSING' : 'differs from what this tool generates'}`); continue; }
  writeFileSync(abs, want, 'utf8');
  wrote.push(`${rel} (${Buffer.byteLength(want)} bytes)`);
}

if (CHECK) {
  if (stale.length) {
    console.error(`parchment --check: ${stale.length} plate(s) not as generated:`);
    for (const s of stale) console.error(`  - ${s}`);
    console.error('  Run `node tools/parchment.mjs` — or, if these were replaced by authored art on');
    console.error('  purpose, that is exactly when this check should be deleted rather than satisfied.');
    process.exit(1);
  }
  console.log(`parchment --check: OK — ${PARCHMENT_ACTS} plate(s), byte-identical to what this tool generates (ext ${PARCHMENT_EXT}).`);
  process.exit(0);
}

console.log(`parchment: ${wrote.length} written, ${PARCHMENT_ACTS - wrote.length} already current.`);
for (const w of wrote) console.log(`  ${w}`);
console.log('BOUNDARY: files written. Nothing here has LOOKED at the result, and nothing here');
console.log('          asserts the bundle carries them — tools/bundle.mjs sweeps assets/ and');
console.log('          tests/engine.test.js is what fails when a plate the code names is absent.');
