-- One immutable content revision. Registry reference tables contain IDs only;
-- names, stats and mechanics remain owned by the existing game registries.
PRAGMA foreign_keys = ON;
CREATE TABLE assets(assetId TEXT PRIMARY KEY NOT NULL, uri TEXT NOT NULL UNIQUE);
CREATE TABLE node_types(nodeTypeId TEXT PRIMARY KEY NOT NULL, displayName TEXT NOT NULL);
CREATE TABLE enemies(enemyId TEXT PRIMARY KEY NOT NULL);
CREATE TABLE encounters(encounterId TEXT PRIMARY KEY NOT NULL);
CREATE TABLE enemy_pools(poolId TEXT PRIMARY KEY NOT NULL, displayName TEXT NOT NULL);
CREATE TABLE enemy_pool_members(poolId TEXT NOT NULL REFERENCES enemy_pools, enemyId TEXT NOT NULL REFERENCES enemies, weight REAL NOT NULL CHECK(weight>0), PRIMARY KEY(poolId,enemyId));
CREATE TABLE regions(regionId TEXT PRIMARY KEY NOT NULL, displayName TEXT NOT NULL, defaultPoolId TEXT NOT NULL REFERENCES enemy_pools);
CREATE TABLE nodes(nodeId TEXT PRIMARY KEY NOT NULL, displayName TEXT NOT NULL, nodeTypeId TEXT NOT NULL REFERENCES node_types, description TEXT NOT NULL, landmarkAssetId TEXT REFERENCES assets);
CREATE TABLE world_nodes(nodeId TEXT PRIMARY KEY NOT NULL REFERENCES nodes, regionId TEXT NOT NULL REFERENCES regions, selectionWeight REAL NOT NULL CHECK(selectionWeight>=0), difficultyAct INTEGER NOT NULL CHECK(difficultyAct BETWEEN 1 AND 3));
CREATE TABLE maps(mapId TEXT PRIMARY KEY NOT NULL, displayName TEXT NOT NULL, artAssetId TEXT NOT NULL REFERENCES assets);
CREATE TABLE world_maps(mapId TEXT PRIMARY KEY NOT NULL REFERENCES maps, authoringTargetNodes INTEGER NOT NULL CHECK(authoringTargetNodes>0));
CREATE TABLE local_maps(mapId TEXT PRIMARY KEY NOT NULL REFERENCES maps, ownerNodeId TEXT NOT NULL UNIQUE REFERENCES world_nodes);
CREATE TABLE world_map_nodes(mapId TEXT NOT NULL REFERENCES world_maps, nodeId TEXT NOT NULL REFERENCES world_nodes, x REAL NOT NULL CHECK(x BETWEEN 0 AND 1), y REAL NOT NULL CHECK(y BETWEEN 0 AND 1), PRIMARY KEY(mapId,nodeId));
CREATE TABLE local_map_nodes(nodeId TEXT PRIMARY KEY NOT NULL REFERENCES nodes, mapId TEXT NOT NULL REFERENCES local_maps, x REAL NOT NULL CHECK(x BETWEEN 0 AND 1), y REAL NOT NULL CHECK(y BETWEEN 0 AND 1));
CREATE TABLE conditions(conditionId TEXT PRIMARY KEY NOT NULL, requiredNodeId TEXT NOT NULL REFERENCES nodes);
CREATE TABLE edges(edgeId TEXT PRIMARY KEY NOT NULL, mapId TEXT NOT NULL, fromNodeId TEXT NOT NULL, toNodeId TEXT NOT NULL, direction TEXT NOT NULL CHECK(direction IN ('forward','both')), conditionId TEXT REFERENCES conditions, CHECK(fromNodeId<>toNodeId), UNIQUE(mapId,fromNodeId,toNodeId), FOREIGN KEY(mapId,fromNodeId) REFERENCES world_map_nodes(mapId,nodeId), FOREIGN KEY(mapId,toNodeId) REFERENCES world_map_nodes(mapId,nodeId));
CREATE TABLE node_enemy_pool_overrides(nodeId TEXT PRIMARY KEY NOT NULL REFERENCES world_nodes, poolId TEXT NOT NULL REFERENCES enemy_pools);
CREATE TABLE node_encounters(nodeId TEXT PRIMARY KEY NOT NULL REFERENCES nodes, encounterId TEXT NOT NULL REFERENCES encounters);
CREATE TABLE service_handlers(handlerId TEXT PRIMARY KEY NOT NULL);
CREATE TABLE service_types(serviceTypeId TEXT PRIMARY KEY NOT NULL, displayName TEXT NOT NULL, handlerId TEXT NOT NULL REFERENCES service_handlers);
CREATE TABLE services(serviceId TEXT PRIMARY KEY NOT NULL, displayName TEXT NOT NULL, serviceTypeId TEXT NOT NULL REFERENCES service_types);
CREATE TABLE node_services(nodeId TEXT NOT NULL REFERENCES nodes, serviceId TEXT NOT NULL REFERENCES services, PRIMARY KEY(nodeId,serviceId));
CREATE TABLE quests(questId TEXT PRIMARY KEY NOT NULL, displayName TEXT NOT NULL, description TEXT NOT NULL, objectiveNodeId TEXT NOT NULL REFERENCES world_nodes, rewardCinders INTEGER NOT NULL CHECK(rewardCinders>=0), speakerId TEXT NOT NULL);
CREATE TABLE node_quests(nodeId TEXT NOT NULL REFERENCES nodes, questId TEXT NOT NULL REFERENCES quests, PRIMARY KEY(nodeId,questId));
CREATE TABLE local_gates(nodeId TEXT NOT NULL REFERENCES local_map_nodes, destinationNodeId TEXT NOT NULL REFERENCES world_nodes, PRIMARY KEY(nodeId,destinationNodeId));
CREATE TABLE anchor_roles(roleId TEXT PRIMARY KEY NOT NULL, displayName TEXT NOT NULL);
CREATE TABLE run_profiles(profileId TEXT PRIMARY KEY NOT NULL, displayName TEXT NOT NULL, profileVersion INTEGER NOT NULL CHECK(profileVersion>0), mapId TEXT NOT NULL REFERENCES world_maps, activeTarget INTEGER NOT NULL CHECK(activeTarget>0), mainMin INTEGER NOT NULL CHECK(mainMin>0), mainMax INTEGER NOT NULL CHECK(mainMax>=mainMin), branchesMin INTEGER NOT NULL CHECK(branchesMin>=0), branchesMax INTEGER NOT NULL CHECK(branchesMax>=branchesMin), allowBacktracking INTEGER NOT NULL CHECK(allowBacktracking IN (0,1)), requireAllRegions INTEGER NOT NULL CHECK(requireAllRegions IN (0,1)), revealRadius REAL NOT NULL CHECK(revealRadius BETWEEN 0.01 AND 0.5), maxAttempts INTEGER NOT NULL CHECK(maxAttempts BETWEEN 1 AND 10000), CHECK(mainMin<=activeTarget));
CREATE TABLE profile_anchors(profileId TEXT NOT NULL REFERENCES run_profiles, roleId TEXT NOT NULL REFERENCES anchor_roles, sequence INTEGER NOT NULL CHECK(sequence>=0), nodeTypeId TEXT NOT NULL REFERENCES node_types, PRIMARY KEY(profileId,roleId), UNIQUE(profileId,sequence));
CREATE TABLE profile_anchor_pins(profileId TEXT NOT NULL, roleId TEXT NOT NULL, nodeId TEXT NOT NULL REFERENCES world_nodes, PRIMARY KEY(profileId,roleId), FOREIGN KEY(profileId,roleId) REFERENCES profile_anchors(profileId,roleId));
CREATE TABLE profile_anchor_exclusions(profileId TEXT NOT NULL, roleId TEXT NOT NULL, nodeId TEXT NOT NULL REFERENCES world_nodes, PRIMARY KEY(profileId,roleId,nodeId), FOREIGN KEY(profileId,roleId) REFERENCES profile_anchors(profileId,roleId));
CREATE TABLE profile_required_services(profileId TEXT NOT NULL, roleId TEXT NOT NULL, serviceTypeId TEXT NOT NULL REFERENCES service_types, PRIMARY KEY(profileId,roleId,serviceTypeId), FOREIGN KEY(profileId,roleId) REFERENCES profile_anchors(profileId,roleId));
CREATE TABLE profile_region_quotas(profileId TEXT NOT NULL REFERENCES run_profiles, regionId TEXT NOT NULL REFERENCES regions, minNodes INTEGER NOT NULL CHECK(minNodes>=0), maxNodes INTEGER NOT NULL CHECK(maxNodes>=minNodes), PRIMARY KEY(profileId,regionId));
CREATE TABLE profile_node_exclusions(profileId TEXT NOT NULL REFERENCES run_profiles, nodeId TEXT NOT NULL REFERENCES world_nodes, PRIMARY KEY(profileId,nodeId));
CREATE TABLE profile_region_exclusions(profileId TEXT NOT NULL REFERENCES run_profiles, regionId TEXT NOT NULL REFERENCES regions, PRIMARY KEY(profileId,regionId));
CREATE TABLE profile_node_weights(profileId TEXT NOT NULL REFERENCES run_profiles, nodeId TEXT NOT NULL REFERENCES world_nodes, weight REAL NOT NULL CHECK(weight>=0), PRIMARY KEY(profileId,nodeId));
CREATE VIEW map_nodes AS SELECT mapId,nodeId,x,y FROM world_map_nodes UNION ALL SELECT mapId,nodeId,x,y FROM local_map_nodes;
CREATE VIEW resolved_node_regions AS SELECT nodeId,regionId FROM world_nodes UNION ALL SELECT n.nodeId,w.regionId FROM local_map_nodes n JOIN local_maps m ON m.mapId=n.mapId JOIN world_nodes w ON w.nodeId=m.ownerNodeId;
CREATE VIEW resolved_service_handlers AS SELECT ns.nodeId,s.serviceId,t.handlerId FROM node_services ns JOIN services s ON s.serviceId=ns.serviceId JOIN service_types t ON t.serviceTypeId=s.serviceTypeId;
