import {prologueTransitionMs} from '../../src/model/prologueTiming.js';
import {paintPrologueCharacter,placePrologueCharacter,CHARACTER_LAYER_HEIGHT} from '../../src/ui/prologueCharacter.js';
import {validateSequence,sceneCopy,motifColour,classIds,sceneNavigation} from './model.mjs';
const $=id=>document.getElementById(id), key='ashenspire.prologue.studio.v1';
const defaults=await fetch('./sequence.json').then(r=>{if(!r.ok)throw new Error('Could not load sequence.');return r.json();});
let data=structuredClone(defaults),index=0,chosenClass='reaver',layout=matchMedia('(max-width:760px)').matches?'mobile':'desktop',playing=false,elapsed=0,last=0,loading=false,revision=0,frame=0;
try{const saved=localStorage.getItem(key);if(saved)data=validateSequence(JSON.parse(saved),defaults);}catch{$('message').textContent='The saved draft could not be read. The original script is available; import a backup to restore edits.';}
let characterImage=null;
function renderCharacter(){if(characterImage){paintPrologueCharacter($('actor'),characterImage,data.presentation.shadowStrength);placePrologueCharacter($('actor'),data.scenes[index].actor[layout]);}}
const asset=id=>new URL(`../../assets/prologue/${id}.webp`,import.meta.url).href;
const sceneAsset=(scene,view,cls)=>asset(`${scene.id==='carry'?'carry-'+cls:scene.id}-${view}`);
const paletteNames={gold:'Goldbough gold',crimson:'Crimson',frost:'Hoarfrost',verdant:'Verdant',violet:'Violet',ember:'Gorefire ember',rot:'Crimson blight',grace:'Lost ember'};
function option(value,text){const o=document.createElement('option');o.value=value;o.textContent=text;return o;}
function save(){try{localStorage.setItem(key,JSON.stringify(data));$('saved').textContent='Saved locally';}catch{$('saved').textContent='Export to save';$('message').textContent='Browser saving is unavailable. Export edits to keep your changes.';}}
function renderCopy(){const scene=data.scenes[index],copy=sceneCopy(scene,data,chosenClass),nav=sceneNavigation(data,index);$('speaker').textContent=copy.speaker;$('dialogue').textContent=copy.text;$('location').textContent=scene.location||'';$('scene-title').textContent=scene.name;$('next').textContent=nav.final?data.labels.setForth:data.labels.continue;$('pause').textContent=playing?data.labels.pause:data.labels.resume;$('counter').textContent=nav.counter;}
function renderTint(){const colour=motifColour(data);document.documentElement.style.setProperty('--accent',colour);$('tint').style.opacity=data.scenes[index].id==='night'?Math.min(data.presentation.wash,.06):data.presentation.wash;$('wash-value').textContent=`${Math.round(data.presentation.wash*100)}%`;}
function renderPalette(){const p=data.presentation;$('palette').replaceChildren(...Object.keys(data.palettes[p.tintSource]).map(id=>option(id,paletteNames[id]||id)));$('palette').value=p.tintSource==='accent'?p.accent:p.characterTint;renderTint();}
function editor(){const scene=data.scenes[index],copy=sceneCopy(scene,data,chosenClass);$('title-input').value=scene.name;$('speaker-input').value=copy.speaker;$('text-input').value=copy.text;$('text-label').textContent=scene.id==='carry'?`${data.classes[chosenClass].name} dialogue`:'Dialogue';$('text-hint').textContent=scene.id==='carry'?'This line is saved only for the selected class. Switch class to edit the other three.':'Changes appear immediately. Line breaks are preserved.';$('seconds').value=scene.seconds;$('effect').value=scene.effect;$('location-row').hidden=!('location' in scene);$('location-input').value=scene.location||'';$('tint-source').value=data.presentation.tintSource;$('wash').value=data.presentation.wash;$('shadow').value=data.presentation.shadowStrength;$('transition').value=data.presentation.transitionSeconds;$('speed').value=data.presentation.speed;$('reduce-motion').checked=data.presentation.reduceMotion;renderPalette();for(const k of Object.keys(data.labels))$(`label-${k}`).value=data.labels[k];}
function renderNav(){[...$('scenes').children].forEach((button,i)=>{button.setAttribute('aria-current',String(i===index));button.querySelector('span').textContent=`${i+1}. ${data.scenes[i].name}`;});}
function picture(src){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(new Error('An art file could not load. Reload the page or check the art pack.'));img.src=src;});}
async function selectScene(i){const token=++revision;index=i;elapsed=0;loading=true;renderCopy();renderNav();editor();$('stage').dataset.layout=layout;$('painting').getAnimations().forEach(a=>a.cancel());$('painting').style.transform='none';try{const scene=data.scenes[index];const [bg,actor]=await Promise.all([picture(sceneAsset(scene,layout,chosenClass)),scene.character?picture(asset(chosenClass)):Promise.resolve(null)]);if(token!==revision)return;$('background').src=bg.src;$('background').alt=scene.name;characterImage=actor;$('actor').hidden=!actor;if(actor){$('actor').setAttribute('aria-label',`${data.classes[chosenClass].name} with ${data.classes[chosenClass].item.toLowerCase()} and ground shadow`);renderCharacter();}if(!data.presentation.reduceMotion&&!matchMedia('(prefers-reduced-motion:reduce)').matches&&scene.effect!=='still'){const effect=scene.effect==='ash'?[{opacity:0,clipPath:'inset(0 0 100% 0)'},{opacity:1,clipPath:'inset(0 0 0 0)'}]:[{opacity:0},{opacity:1}];$('painting').animate(effect,{duration:prologueTransitionMs(scene,data.presentation),fill:'none',easing:'ease-out'});}}catch(e){$('message').textContent=e.message;playing=false;}finally{if(token===revision){loading=false;last=0;renderCopy();}}}
function tick(now){if(last&&playing&&!loading&&!document.hidden){elapsed+=(now-last)/1000*data.presentation.speed;const scene=data.scenes[index];if(scene.effect==='push'&&!data.presentation.reduceMotion&&!matchMedia('(prefers-reduced-motion:reduce)').matches)$('painting').style.transform=`scale(${1+Math.min(elapsed/scene.seconds,1)*.03})`;if(elapsed>=scene.seconds){const next=sceneNavigation(data,index).next;if(next!==null)selectScene(next);else{elapsed=scene.seconds;playing=false;renderCopy();}}}last=now;const duration=data.scenes[index].seconds;$('progress').style.width=`${Math.min(elapsed/duration,1)*100}%`;$('time').textContent=`${Math.floor(elapsed)} / ${duration}s`;frame=requestAnimationFrame(tick);}
function setPlaying(value){playing=value;last=0;$('painting').getAnimations().forEach(a=>value?a.play():a.pause());renderCopy();}
function mutate(fn){fn();save();renderCopy();renderTint();renderNav();}
for(const id of classIds)$('class').append(option(id,data.classes[id].name));$('layout').value=layout;
for(const [i,scene]of data.scenes.entries()){const b=document.createElement('button');b.type='button';const img=document.createElement('img');img.src=sceneAsset(scene,'desktop',chosenClass);img.alt='';const span=document.createElement('span');b.append(img,span);b.addEventListener('click',()=>{setPlaying(false);selectScene(i);});$('scenes').append(b);}
for(const k of Object.keys(data.labels)){const label=document.createElement('label');label.textContent=({continue:'Continue button',setForth:'Final button',pause:'Pause button',resume:'Resume button',replay:'Replay button'})[k];const input=document.createElement('input');input.id=`label-${k}`;input.maxLength=100;input.addEventListener('input',()=>mutate(()=>data.labels[k]=input.value));label.append(input);$('label-editor').append(label);}
$('class').onchange=()=>{chosenClass=$('class').value;selectScene(index);};$('layout').onchange=()=>{layout=$('layout').value;selectScene(index);};
$('title-input').oninput=e=>mutate(()=>data.scenes[index].name=e.target.value);
$('speaker-input').oninput=e=>mutate(()=>{const s=data.scenes[index];if(s.speaker==='{class}')data.classes[chosenClass].name=e.target.value;else s.speaker=e.target.value;});
$('text-input').oninput=e=>mutate(()=>{const s=data.scenes[index];if(s.id==='carry'&&s.text==='{classLine}')data.classes[chosenClass].line=e.target.value;else s.text=e.target.value;});
$('location-input').oninput=e=>mutate(()=>data.scenes[index].location=e.target.value);
function bindNumber(id,min,max,update){$(id).onchange=e=>{const n=Number(e.target.value);if(!Number.isFinite(n)||n<min||n>max){e.target.reportValidity();editor();return;}mutate(()=>update(n));};}
bindNumber('seconds',1,180,n=>data.scenes[index].seconds=n);bindNumber('transition',0,30,n=>data.presentation.transitionSeconds=n);bindNumber('speed',.25,3,n=>data.presentation.speed=n);
$('shadow').oninput=e=>{mutate(()=>data.presentation.shadowStrength=Number(e.target.value));renderCharacter();};
$('effect').onchange=e=>{mutate(()=>data.scenes[index].effect=e.target.value);selectScene(index);};$('tint-source').onchange=e=>{data.presentation.tintSource=e.target.value;renderPalette();save();};$('palette').onchange=e=>mutate(()=>data.presentation[data.presentation.tintSource==='accent'?'accent':'characterTint']=e.target.value);$('wash').oninput=e=>mutate(()=>data.presentation.wash=Number(e.target.value));$('reduce-motion').onchange=e=>{mutate(()=>data.presentation.reduceMotion=e.target.checked);$('painting').style.transform='none';$('painting').getAnimations().forEach(a=>a.cancel());};
$('play').onclick=async()=>{setPlaying(false);await selectScene(0);setPlaying(true);};$('pause').onclick=()=>setPlaying(!playing);$('next').onclick=()=>{const next=sceneNavigation(data,index).next;if(next!==null)selectScene(next);else{setPlaying(false);elapsed=data.scenes[index].seconds;$('message').textContent='End of the art preview. In the game, this is where the first node will appear.';}};
document.addEventListener('visibilitychange',()=>{if(document.hidden)setPlaying(false);});
function download(blob,name){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
$('export').onclick=()=>{try{const checked=validateSequence(data,defaults);download(new Blob([JSON.stringify(checked,null,2)],{type:'application/json'}),'ashenspire-opening-preset.json');$('message').textContent='Exported all scenes, four class lines, button text, timing, and motif settings.';}catch(e){$('message').textContent=e.message;}};
$('import').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>250000)throw new Error('Preset is too large (maximum 250 KB).');const next=validateSequence(JSON.parse(await file.text()),defaults);setPlaying(false);data=next;save();await selectScene(index);$('message').textContent='Imported all opening edits.';}catch(error){$('message').textContent=`Import refused: ${error.message} Your existing edits were kept.`;}finally{e.target.value='';}};
$('reset').onclick=()=>{if(!confirm('Restore the original script and settings? Export edits first if you want a backup.'))return;setPlaying(false);data=structuredClone(defaults);save();selectScene(index);};
$('download').onclick=async()=>{const button=$('download');button.disabled=true;try{const scene=structuredClone(data.scenes[index]),heldClass=chosenClass,heldLayout=layout,shadowStrength=data.presentation.shadowStrength,colour=motifColour(data),wash=scene.id==='night'?Math.min(data.presentation.wash,.06):data.presentation.wash;const [bg,actor]=await Promise.all([picture(sceneAsset(scene,heldLayout,heldClass)),scene.character?picture(asset(heldClass)):Promise.resolve(null)]);const canvas=document.createElement('canvas');canvas.width=bg.naturalWidth;canvas.height=bg.naturalHeight;const ctx=canvas.getContext('2d');ctx.drawImage(bg,0,0);if(actor){const a=scene.actor[heldLayout],h=canvas.height*a.height/100,layer=paintPrologueCharacter(document.createElement('canvas'),actor,shadowStrength),w=h*layer.width/actor.naturalHeight;ctx.drawImage(layer,canvas.width*a.x/100-w/2,canvas.height*a.y/100-h,w,h*CHARACTER_LAYER_HEIGHT);}ctx.globalCompositeOperation='color';ctx.globalAlpha=wash;ctx.fillStyle=colour;ctx.fillRect(0,0,canvas.width,canvas.height);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/webp',.94));if(!blob)throw new Error('Could not encode the WebP image.');download(blob,`${scene.id}-${scene.character||scene.id==='carry'?heldClass+'-':''}${heldLayout}.webp`);$('message').textContent='Downloaded text-free artwork with the selected class and motif.';}catch(error){$('message').textContent=error.message;}finally{button.disabled=false;}};
$('download-character').onclick=async()=>{try{const id=chosenClass,strength=data.presentation.shadowStrength;const source=await picture(asset(id)),layer=paintPrologueCharacter(document.createElement('canvas'),source,strength);const blob=await new Promise(resolve=>layer.toBlob(resolve,'image/webp',.94));if(!blob)throw new Error('Could not encode the character layer.');download(blob,`${id}-with-shadow.webp`);$('message').textContent='Downloaded the transparent character layer with its ground shadow.';}catch(error){$('message').textContent=error.message;}};
window.addEventListener('pagehide',()=>cancelAnimationFrame(frame));
await selectScene(0);save();frame=requestAnimationFrame(tick);
